eclipse-thingweb/node-wot

- packages/cli/src/default-servient.ts
the servient crashed when running via cli resp. generally when running  default config, as this does not contain config.credentials (also config is null).
> safeguard config.credentials to avoid null-ref 

- packages/td-tools/src/td-parser.ts
- packages/td-tools/src/thing-description.ts
- packages/td-tools/test/TDParseTest.ts
See https://github.com/eclipse/thingweb.node-wot/issues/32
AND auto-format td-parser.ts
Note1: by default use http and not https context uri
Note2: for compatibility reasons still allow "old" namespaces
> fix: node-wot issue#32 about NS contexts

- packages/core/src/exposed-thing.ts
fix(core): fix unhandled property write rejection
if the promise returned by a custom writeHandler for a property of ExposedThing is rejected, this rejection should be handled.
fixes #54
> fix(core): fix unhandled property write rejection

- packages/core/src/consumed-thing.ts
this line crashes when I try to access a thing that is secured by a "scheme": "bearer"
https://github.com/eclipse/thingweb.node-wot/blob/master/packages/core/src/consumed-thing.ts#L123
> fixing a crash when using client with security

- examples/scripts/wot-servient.conf.json
- packages/cli/src/cli.ts
cli: add mqtt information on the output of wot-servient -h
Signed-off-by: Ege Korkan <egekorkan@gmail.com>
> fix: remove username, password and clientid from default config

- packages/binding-http/src/http-client.ts
HttpClient says it will overwrite the local proxy if a security proxy is given. however, a bug prevented this from happening.
> fix(binding-http): correctly use security proxy

- packages/binding-http/package.json
- packages/binding-http/src/http-client.ts
- packages/binding-http/test/http-client-test.ts
When a subscription returns a response with an error code, don't keep polling forever.
Right now, when a subscription return a 404 for example (not a request error), polling() is directly called again, and return another 404, which results in an endless loop.
> fix(http-binding): stop polling in case of error

- README.md
- packages/cli/src/cli.ts
- packages/core/src/servient.ts
Vm scripts must have `filename` option to be inspected. Filename option allows the node inspector to locate script source files and to support breakpoints inside the script. 
Example:
`node --inspect-brk packages/cli/dist/cli.js ../thing.js`
Futher details on [docs](https://nodejs.org/api/vm.html#vm_class_vm_script).
> Add support for debugging thing scripts

- packages/binding-mqtt/src/mqtt-broker-server.ts
Added features:
- Before the `expose()` returns, the TD is published to the broker, addresses issue #144. This is also published with retain set to true
- readOnly and writeOnly properties are handled. Before even writeOnly properties were readable and there was no way to write to properties via MQTT. Now, only readable properties are published to and there is handling of subscribed topics to handle writing, like with actions. Addresses issue #152 
I am not able to write tests for this due to 2 reasons:
1. See #161 
2. A test for this would require to fetch the TD from the broker. This is not possible with the `fetch()` function since it always maps to `readResource()` which is not implemented in the mqtt binding. Then I have tried the following but was blocked by the same reason as in …
> MQTT features

- packages/binding-coap/README.md
see https://github.com/eclipse/thingweb.node-wot/issues/157
> feat: create readme for CoAP binding package

- examples/servients/netconf-cli/package.json
- examples/servients/opcua-cli/package.json
- packages/binding-opcua/README.md
PR for fixing #182.
package.json for netconf cli and opcua cli updated for installing the latest snapshot of netconf and opcua bindings.
Signed-off-by: lukesmolo <lukesmolo@gmail.com>
> fix(binding-netconf, binding-opcua): package.json update for netconf cli and ocpua cli.

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
see https://github.com/eclipse/thingweb.node-wot/issues/181
besides the fix it also changes the internal variable name "securityScheme" to "httpSecurityScheme" to make clear the difference
> fix: allow explicitely configure no security in HTTP

- packages/examples/package.json
- packages/examples/tsconfig.json
As @fatadel as pointed out I made some mistakes in #235 . This PR fixes the examples `tsconfig` and `package` files
> Fix examples

- packages/cli/README.md
- packages/cli/src/cli-default-servient.ts
- packages/cli/wot-servient.conf.json.md
This PR closes #193.
Among adding support for the log levels, I have also slightly changed the levels themselves.
Originally, in `packages/cli/wot-servient.conf.json.md` it states "LEVEL is a string or number to set the logging level: `{ error: 0, warn: 1, info: 2, log: 3, debug: 4 }`". But I have changed it to `{ error: 0, warn: 1, info: 2, debug: 3 }` removing the level `log` since I find it quite silly to suppress `console.log` level messages. I've made the level `info` as default which is pretty logical and it also was the default level in the `examples/scripts/wot-servient.conf.json` config file.
> feat: add log levels

- packages/binding-http/src/http-client.ts
As the title implies, while I was working on #258 example I noticed that the response code of invoke resource request was not validated. This PR adds the validation function before returning the result of the action.
> fix(http-client): check invoke resource response status

- packages/binding-mqtt/package.json
- packages/binding-mqtt/src/mqtt-broker-server.ts
The library we use changed some stuff around, now everything is a `Buffer`, so we need to handle that.
Additionally 32f787951c5ad29f444e1ab41fc4b46e3f592a74 contained a partial fix, which lead to the behavior observed in #224.
Fixes #224.
> fix(binding-mqtt): pass along mqtt payload properly

- packages/browser-bundle/README.md
init a readme for the browser bundle. Current situation: https://www.npmjs.com/package/@node-wot/browser-bundle
> Missing Readme for browser bundle

- packages/td-tools/src/td-parser.ts
Note: causes lots of noise in HTTP observe
caller may still to do logging if required/wanted
> fix: issue 244, avoid logging serialized TD every time

- .vscode/launch.json
This PR closes #245. it introduces a set of *vscode* launch tasks to easily debug/launch the tests defined in each package.
> Add vscode tasks for package testing

- README.md
To document how to install node-wot tools as local dependencies that in turn can run scripts using other local dependencies.
Closes #289
@relu91 please check if this is according with how node-wot is intended to be used.
If not, changes may be necessary to properly support the management of local dependencies.
> #289 update README

- examples/security/oauth/README.md
- examples/security/oauth/consumer.js
- examples/security/oauth/exposer.js
- examples/security/oauth/memory-model.js
- examples/security/oauth/package.json
- examples/security/oauth/server.js
- examples/security/oauth/wot-server-servient-conf.json
- packages/binding-http/package.json
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/core/src/consumed-thing.ts
- packages/examples/src/security/oauth/consumer.ts
- packages/examples/src/security/oauth/exposer.ts
- packages/examples/src/security/oauth/memory-model.js
- packages/examples/src/security/oauth/package.json
- packages/examples/src/security/oauth/server.js
- packages/examples/src/security/oauth/wot-server-servient-conf.json
This PR introduces token validation for OAuth tokens in HTTP server implementation. OAuth token validation can be carried out using different methods. This PR uses a standard protocol to request token validation to a `introspection-endpoint`. Specifically, the protocol is defined in [RFC7662](https://tools.ietf.org/html/rfc7662) and it defines how a resource server interacts with the authorization server to validate a token. The protocol is quite flexible but it has some security implications and therefore it is advised to be used with caution. For example, the `introspection-endpoint` must be not visible to other clients or it must be protected using an authentication method (basic or even OAuth again).
This PR is still a draft because I want to complete the OAuth example with also the …
> [http-binding] OAuth server side token validation 

- packages/binding-http/src/http-client.ts
- packages/binding-http/src/subscription-protocols.ts
- packages/binding-http/test/http-client-test.ts
The problem was caused by the fact that the event connection was never closed. Now the EventSource is correctly closed when `unlinkResource` is called.
The PR is still WIP because I want to add a refactor to keep `http-client` code a little bit clean. But first I want to check that Travis do not fail.
> [binding-http] fix multiple done called in sse tests

- Dockerfile
This PR provides two contributions:
1. fixes the docker build file. After #186 docker builds failed due to missing system dependencies. Now it correctly install also g++, linux-headers and udev (serial-port requires them for building).   
2. it reduces the size of the final image from about 650 Mb to 140 Mb.
> Optimize docker build

- packages/binding-file/src/file-client.ts
- packages/core/src/core.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/19
fixes also file-client to use provided contentType if possible
> feat: exports built-in codecs

- packages/binding-coap/src/coap-server.ts
- packages/binding-http/src/http-server.ts
add "unsubscribeevent" and "unobserveproperty" for HTTP
add "observeproperty", "unobserveproperty", and "unsubscribeevent" for CoAP
> feat: add missing op fields

- README.md
Currently, the WebSocket client does not have any functionality implemented. Therefore, I changed the main readme to reflect the real status.
> Correct websocket implementation status

- packages/browser-bundle/package.json
- packages/core/package.json
- packages/core/src/servient.ts
- packages/core/test/RuntimeTest.ts
This PR closes #314. As described in the issue vm2 has a couple of benefits. In particular, it will solve problems for `require` calls in WoT application scripts ( #191). With subsequent PRs we could close issues #190 #192 #275, without major modifications. Probably also #185 might be resolved thanks to the `transpilers` support of vm2.
> Upgrade to vm2

- packages/cli/src/cli.ts
- packages/core/src/servient.ts
This PR is based on #315 so I put this as a draft until #315 is merged. It closes #275 introducing the ability to pass command-line arguments to WoT Scripts. I choose the same syntax used by npm and other CLIs. Basically, to recognize which arguments should be passed and which argument should be used by the CLIs I used `--` as a separator. For example in the following command line:
```bash
wot-servient -c config.js script1.js script2.js -- -option arg1 arg2
```
`-c`, `config.js`, `script1.js`, and script2.js are interpreted by our CLI package whereas `-option`, `arg1`,and arg2 can be read by **both** script1.js and script2.js.
This means that scripts can have the same argument without conflicts: 
```bash
wot-servient script1.js script2.js -- -c config.js
```
Node-wot cli does not read the …
> Introduce WoT scripts command line args

- packages/core/src/servient.ts
- packages/core/test/RuntimeTest.ts
This PR adds missing tests for the new "passing args" feature. I required a small refactor but I think it was necessary and it might be useful in the future to enable a servient/script communication.
> [Core] small refactoring with runScript  tests

- packages/binding-http/README.md
- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
and when we override with an environment variable, let's actually tell the user!
This is the  PORT side of the issue I raised in  #214   The BaseURI is in #220 
The current implementation silently overrides the port.  This change shows a clear message that it has been overridden.
it also adds an additional environment variable WOT_PORT which will take precedence over PORT if present. This is to allow node-wot implementations that coexist with another web server in the same container, such as nodejs, ruby on rails, nginx/apache for static assets etc.  
Test and documentation included
In #214 I also mentioned running into this, where both servers were trying to bind to the PORT value specified by the heroku build pack.
@danielpeintner I saw your recent env-var PR #319 was merged, so I …
> improve http PORT env var situation

- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/src/servient.ts
- packages/core/test/RuntimeTest.ts
This PR add supports for custom compilers in the Servient runtime. Currently, I tested only `ts-node` but in principle also others might work. I managed to run this simple script inside `node-wot`:
```ts
/// <reference types="../types/wot" />
WoT.produce({}).then( (thing:WoT.ExposedThing) => {
console.log(thing.getThingDescription().id)
})
```
to run it: `npm i ts-node && wot-servient --compiler ts-node main.ts` 
**Notice**: I used wam typescript project template (i.e. custom type definitions) and I needed to use `/// <reference types="../types/wot" />` (see point 2 below). 
.However, there still a couple of open points:
1. `cli.ts` is getting pretty messy. I think It wasn't originally designed to be a simple interface, now it is evolved in a quite complex command-line tool. Probably it …
> [CLI/core] custom compilers

- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
* adds tests also
fixes https://github.com/eclipse/thingweb.node-wot/issues/326
> feat: check whether property is readOnly or writeOnly on exposed-thing

- examples/scripts/smart-coffee-machine-client.conf.json
- examples/scripts/smart-coffee-machine-oauth.js
- packages/examples/src/scripts/smart-coffee-machine-oauth.ts
This PR resolves naming differences for the smart coffee machine that were not spotted in https://github.com/eclipse/thingweb.node-wot/pull/330.
> feat: align coffee machine namings

- examples/scripts/smart-coffee-machine-oauth.js
- examples/scripts/smart-coffee-machine.js
- packages/core/test/ServerTest.ts
- packages/examples/src/scripts/smart-coffee-machine-oauth.ts
- packages/examples/src/scripts/smart-coffee-machine.ts
> feat: refine promise usages in smart coffee machine scripts

- packages/core/src/servient.ts
- packages/core/test/RuntimeTest.ts
In #315 we updated node-wot to use [vm2](https://www.npmjs.com/package/vm2) module. Since [vm2](https://www.npmjs.com/package/vm2) is more restrictive, it needs to be manually set to support builtin modules require.
> Fix WoT scripts cannot require builtin modules

- packages/binding-http/src/subscription-protocols.ts
The longpoll client doesn't work giving an `UnhandledPromiseRejectionWarning: ReferenceError: closed is not defined` exception.
This PR fixes the error.
> fix: fix longpoll client

- packages/binding-http/README.md
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/test/http-server-test.ts
Related issues #214,  #878
TLDR:
> Implement 'base' property, and test, via
````
Assume thing.base = "http://all.your.base.are.belong.to.us:9999"
urlbase = thing.base || ( this.scheme + "://" + address + ":" + this.getPort() );
let href = base + "/" + this.ALL_DIR + "/" + encodeURIComponent(this.ALL_PROPERTIES);
console.log(href)
=> ":"http://all.your.base.are.belong.to.us:9999/WOT/all/properties" 
````
According to the language in the spec, the implied assumption is that the form, action, property URLs are relative, and relative to the base URI.
> base property: Define the base URI that is used for all relative URI references throughout a TD document. In TD instances, all relative URIs are resolved relative to the base URI using the algorithm defined in [RFC3986].
> base does not affect …
> BaseURI for links in TD

- .travis.yml
- packages/binding-netconf/test/netconf-client-test.ts
This PR fixes `netconf` tests that failed on my windows machine. It was basically just a time issue. The tests are verifying the correct behavior when the `netconf` server is not online. In my windows version, the operating systems give up just after 2000 ms which is the default mocha time out. Increasing the timeout solved the issue.  
As you can see from the commit logs the PR also adds windows as a testing platform in travis. I thought it might worth it since now it seems that all the tests are green.
> Fix netconf tests

- packages/binding-http/test/oauth-token-validation-tests.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/367
> fix: wait for the server to start before continuing the HTTPS test

- packages/binding-coap/package.json
- packages/binding-coap/src/coap-client.ts
Fixes #363.
Bump versions for packages `node-coap-client` and `coap`. 
`node-coap-client` had an [similar issue with IPv6](https://github.com/AlCalzone/node-coap-client/issues/253). This bump should avoid it in the coaps implementation. 
Not a very nice implementation btw, but it doesn't change the API too much. It keeps everything quite stable. 
**Please test with IPv4. Only tested it with coap on IPv6.**
> #363 Fix: Use udp6 for IPv6 and udp4 for legacy IP

- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.ts
This PR is a very simple fix/workaround for #255: The leading `/` that is currently derived from the URI path is being removed. As most MQTT topics should not feature a leading `/` (among other things, because it is not best practice to so, see #255) this fix should not cause much harm while making it possible to actually use `node-wot` with the majority of MQTT devices.
> fix: Remove leading "/" from MQTT topics

- packages/examples/src/scripts/counter.ts
According to #171 and `packages/examples/README.md`, PR #413 should also fix the typescript counterpart of counter.js
Signed-off-by: Iori Mizutani <iori.mizutani@gmail.com>
> fix: sync counter.ts with counter.js

- examples/scripts/counter-client.js
- packages/examples/src/scripts/counter-client.ts
When I run the example for the counter thing and its consumer `examples/scripts/counter-client.js` I get the error `ConsumedThing 'counter' missing formIndex '2'`:
```
vagrant@ubuntu-focal:/vagrant/thingweb.node-wot$ node packages/cli/dist/cli.js examples/scripts/counter-client.js -
-clientonly
[cli] WoT-Servient using defaults as 'wot-servient.conf.json' does not exist
{
servient: { clientOnly: true, scriptAction: false },
http: { port: 8080, selfSigned: false },
coap: { port: 5683 },
log: { level: 'info' }
}
[cli/default-servient] DefaultServient started
[core/servient] Servient generating ID for 'servient': 'urn:uuid:8b2cc2c6-2354-49b2-8b1c-fee5f9fd1351'
[core/servient] Servient has no servers to expose Things
[cli] WoT-Servient loading 1 command line script
[cli] WoT-Servient reading …
```
> fix: examples/scripts/counter-client.js formIndex

- Dockerfile
- README.md
I've added the following:
- `docker build` instruction for wot-servient
- "No time for explanations" example using Docker
To make the built Docker image a bit more useful, I also added `STOPSIGNAL SIGINT` to `Dockerfile`.
> docs: Docker example

- .vscode/tasks.json
VS code deprecated v1.0.0 version of the task file, considering that vscode is usually automatically updated I think we are safe to upgrade the task file to v2.0.0. Plus it doesn't really like the file and every time a user oper the repository it automatically replaces it with the new version.
> Upgrade tasks file to v2.0.0

- packages/binding-modbus/README.md
A minor PR with an example of how bytes are encoded using different byte orders.
> Add an example for modbus encoding

- packages/core/package-lock.json
- packages/core/package.json
- packages/core/src/codecs/octetstream-codec.ts
- packages/core/test/ContentSerdesTest.ts
This PR fixes issues #448 and #447.  Notice that `@type` is not used as the source of information for the encoding format. The library now uses `type` and a set of well know identifiers for complex types like `uint8`.
> Octet stream encoding process and support for float16

- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-mqtt/src/mqtt.ts
- packages/binding-mqtt/src/mqtts-client-factory.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.ts
This PR should fix #455. I used a conservative style but the MQTT binding need multiple updates to put it in shape. Moreover, I did not test the change for custom self-signed certificate validation. People can use `rejectUnauthorized: false` meanwhile, but it is considered a temporary solution just for internal testing.
> Connect to mqtts

- packages/binding-wotfirestore-browser-bundle/README.md
- packages/binding-wotfirestore-browser-bundle/index.js
- packages/binding-wotfirestore-browser-bundle/package-lock.json
- packages/binding-wotfirestore-browser-bundle/package.json
- packages/binding-wotfirestore/README.md
- packages/binding-wotfirestore/package-lock.json
- packages/binding-wotfirestore/package.json
The package name has been changed to the following.
* @node-wot/binding-wotfirestore
* @node-wot/binding-wotfirestore-browser-bundle
The version was set to 0.7.8 to match the other versions of thingwot.
I have also changed the other packages of thingweb used by binding-wotfirestore to 0.7.8.
> change package name and versions for binding-wotfirestore

- package-lock.json
- packages/binding-coap/package.json
This PR updates the `coap` package used in the `binding-coap` package. As the new version now also supports the `application/td+json` Content-Format, this PR makes it possible to also fetch TDs which are provided as such without throwing an error.
This behavior fixed in the new version in general, so an invalid Content-Format cannot cause an application to crash anymore.
> chore(binding-coap): bump node-coap to 0.25.0

- .github/workflows/ci.yaml
- CONTRIBUTING.md
This PR is intended to be a follow-up to #493 and adds both a linting action (using eslint) and style check action (using prettier) to the CI. Both actions are currently failing because there the code base is not yet formatted correctly but once #493 is completed all checks will hopefully turn green :)
I am not sure yet, however, if the prettier action is configured correctly (or if it should be swapped out for a similar prettier action) as it does not add annotations in the "files changed" tab yet. I will have a look into that.
> chore: Add linting and code style checks to the CI

- packages/binding-mqtt/src/mqtt-client.ts
I found a minor bug in the `binding-mqtt/src/mqtt-client.js` lines 70 and 76 with a duplicate `error` definition (in subscribeResource() and then again in "error" handler).
This PR simply changes lines 70 and 76 to fix this.
This was throwing the following error:
```bash
[ERROR] 17:13:25 TypeError: error is not a function
```
> fix(binding-mqtt): fix 'TypeError: error is not a function"'

- .github/workflows/ci.yaml
This PR replaces the external Github Action for `eslint` by first installing it using `npm ci` and then running `npm run lint`. This removes the action as one additional dependency and also replicates the local environment for linting while still keeping the annotations made in the "Files changed" tab.
Furthermore, this PR lets the linting workflow pass even if errors occur, making it easier to see if there is an actual failing test. Once all linting issues have been resolved, this addition can be removed again.
> chore: replace external eslint action, continue on failure

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
This PR removes the unnecessary registration of the content-format `application/td+json` from the coap package. It is now supported [by default](https://github.com/mcollina/node-coap#coapregisterformatname-value) in `node-coap`, using the correct [IANA ID 432](https://www.iana.org/assignments/core-parameters/core-parameters.xhtml#content-formats).
> fix(coap): Remove double registration of TD content-format

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/interaction-output.ts
Note: this PR is not meant to be merged as is.
I just run the counter sample and with the current code I get
```
[binding-http] HttpServer on port 8080 got internal error on read '/counter/properties/count': Converting circular structure to JSON
--> starting at object with constructor 'ReadableStream'
|     property '_readableStreamController' -> object with constructor 'ReadableStreamDefaultController'
--- property '_controlledReadableStream' closes the circle
```
I tried to fix it but I am not sure whether this is the right way...
> fix: http server reporting circular structure

- .prettierignore
A trivial PR that just ignore dist folders for prettier
> chore: ignore dist folder in formatting

- packages/binding-coap/src/coap-client.ts
- packages/core/src/protocol-helpers.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/522
Note1: tested with counter sample using CoAP for all forms.
Note2: I would like to tackle https://github.com/eclipse/thingweb.node-wot/issues/523 in a separate PR.
> fix: allow invokeResource without any parameter (CoAP client)

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap.ts
- packages/binding-coap/src/coaps-client.ts
- packages/binding-coap/test/coap-client-test.ts
While having a look at the current CoAP implementation in the context of #523, I noticed that the vocabulary that is being used is not up to date with the current binding-templates. This PR should fix this and should provide the basis for fixing #523.
> fix: align CoAP vocabulary with current binding-templates

- packages/binding-coap/src/coap.ts
This is a minor fix for the `coap` package replacing the wrong type  `number` of `cov:optionName` with `string`.
> fix(coap): use string type for option name

- package-lock.json
- packages/binding-fujitsu/package.json
- packages/binding-mbus/package.json
- packages/binding-mqtt/.eslintrc.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/.eslintrc.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-oracle/.eslintrc.json
- packages/binding-oracle/package.json
- packages/binding-websockets/.eslintrc.json
- packages/binding-websockets/package.json
- packages/browser-bundle/.eslintrc.json
- packages/browser-bundle/package.json
- packages/core/package.json
- packages/examples/.eslintrc.json
- packages/examples/package.json
This PR should resolve #530 by adding missing eslint and prettier configs. At the moment, I added the additional eslint configs to the package.json files as I thought it might make the packages cleaner in general. However, I now think it might be better to have separate `.eslintrc.json` files to make it easier to see if an eslint configuration exists. Let me know what you think about this :)
There is currently still an issue in the `examples` package where the `npm run lint` script fails with the following error message:
```
Oops! Something went wrong! :(
ESLint: 7.32.0
No files matching the pattern "." were found.
Please check for typing mistakes in the pattern.
```
Do you have an idea how to fix this?
> chore: add missing eslint and prettier configs

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/coap.ts
- packages/binding-coap/src/coaps-client-factory.ts
- packages/binding-coap/src/coaps-client.ts
- packages/binding-coap/test/coap-client-test.ts
- packages/binding-file/src/file-client-factory.ts
- packages/binding-file/src/file-client.ts
- packages/binding-http/src/credential.ts
- packages/td-tools/test/TDTransformerTest.ts
The second portion of eslint alignments (previous one - https://github.com/eclipse/thingweb.node-wot/pull/511).
> refactor: align with eslint rules #2

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
- packages/core/src/exposed-thing.ts
This PR adds support for input/output roundtripping in exposed things with the new API. Notice that this is still a work in progress and we will need to change also al the other affordances and methods. 
The idea behind this PR is to provide protocol bindings a dedicated interface where they can communicate with the upper core level (i.e., exposed thing). Before `ConsumeThing` methods were used but I think it is better to provide a simpler interface where bindings just exchange `Content` instances.
> Add support for streams in action handlers

- packages/td-tools/src/td-parser.ts
- packages/td-tools/src/thing-description.ts
Note: uses eslint-disable for any usage in TD
1. TD class should be replaced by auto-generated one (see https://github.com/eclipse/thingweb.node-wot/issues/529)
2. At the moment methods are attached in various places
Note: added to https://github.com/eclipse/thingweb.node-wot/issues/534
> fix(td-tools): resolve eslint issues

- examples/servients/opcua-cli/src/cli-opcua-servient.ts
- examples/servients/opcua-cli/src/opcua-cli.ts
- packages/binding-opcua/tsconfig.json
Update for opcua servient cli. Please note that, in order to build the cli, the local packages must be linked through _npm link_, fixed by #609, since in the package.json the version for the required bindings is not available through npm. Furthermore, it seems that the _tsconfig_ for binding-opcua was compiling everything into _dist/src_, in fact making not available for the opcua cli the binding-opcua package through the link operation.
> Opcua servient cli

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
This PR tries to fix the issues when you want to try our counter example like the following:
`node packages/cli/dist/cli.js examples/scripts/counter.js` and `node packages/cli/dist/cli.js --clientonly examples/scripts/counter-client.js`. I've just fixed a small issue but there is more ahead, that's why the PR is in a draft status.
> Fix coap binding with regards to counter example

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/coap.ts
- packages/binding-coap/test/coap-client-test.ts
- packages/binding-coap/typings/coap/index.d.ts
This PR will update the `binding-coap` package with typescript declarations from `node-coap` (see https://github.com/mcollina/node-coap/pull/278) once a new version is released. It includes my local adjustments used for checking that the type declarations are actually usable. There are a small number of `any`s which still have to be fixed but other than that a large amount of code will be covered now with proper typing.
I also noticed ~~two bugs~~ one minor issue in the `coap` package due to the new type declarations for which I will open a separate PR for an immediate fix.
> feat(coap): update type definitions

- package.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
This PR adds a `lint:fix` script to every package to automatically apply eslint fixes (if possible).
> chore: add `lint:fix` npm scripts

- .eslintrc.js
- package-lock.json
- package.json
In #635 I noticed that sometimes tools like vscode might use relative imports when working on one of the packages. To avoid problems down the road (i.e. after publication or build time) I've added this simple eslint that warns us if there are some wrong imports. It has just a small issue on windows that I fixed in https://github.com/joshuajaco/eslint-plugin-workspaces/pull/17, I hope to get it merged soon.
> Add eslint workspaces import validator

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
This PR updates the `node-coap` dependency to the new major release. There are still a couple of minor issues that have to be resolved first, however (see https://github.com/mcollina/node-coap/pull/322), which is why I opened this PR as a draft for now.
> chore(coap): update node-coap to version 1.x.x and fix type issues

- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-client.ts
- packages/binding-http/test/credential-test.ts
With these changes, the HTTP-binding now correctly uses the information in `SecurityScheme` to configure a request object. In particular, they focus on handling correctly the parameter `name`.
Fixes #631
cc: @fillobotto
> Handle security scheme `name` in http binding

- LICENSE.md
This trivial PR updates the LICENSE file with the year 2021. 
As 2022 is not far away anymore: Maybe this file could also be updated in the copyright header script?
> chore: update copyright year in LICENSE file

- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-coap/src/coap-server.ts
- packages/td-tools/package.json
After the latest update of node-coap, the type-casting introduces by #634 can now be removed as the `OutgoingMessage` class now provides the correct type information regarding the interfaces it implements.
This PR updates node-coap to the latest version and removes the now obsolete type casting. Resolves https://github.com/eclipse/thingweb.node-wot/issues/642.
> fix(coap-server): remove type casting to unknown

- packages/binding-modbus/README.md
The `length` content-type parameter is not properly introduced in the modbus readme. This PR adds an explanation about the `length` purpose.
> Add a brief introduction for the length content-type parameter

- packages/binding-modbus/src/modbus-client-factory.ts
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/src/modbus.ts
- packages/binding-modbus/test/modbus-client-test.ts
- packages/binding-modbus/test/modbus-connection-test.ts
- packages/binding-modbus/test/test-modbus-server.ts
This PR fixes most of the eslint issues in the Modbus binding. There are still a couple of `any`s which will have to be revisited as well as some errors due to the order of interface definitions but those should (once more) be dealt with in a follow-up PR.
> style(binding-modbus): resolve linting issues

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/test/coap-server-test.ts
This PR supersedes #625 by adding the option `{reuseAddr: false}` to node-coap's CoAP server. This prevents port reuse as discussed in #625..
The PR also reintroduces and improves the respective test that has been commented out so far.
Resolves #523.
> fix(coap-server): Don't allow port reuse, reintroduce test

- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-netconf/src/netconf-client-factory.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-netconf/src/xpath2json.ts
- packages/binding-netconf/test/netconf-client-test.ts
This PR resolves most of the eslint errors and warnings in the `binding-netconf` package. Unfortunately, a number of `any`s had to be introduced as a number of parameters and types require a bit more work than expected. These should probably be introduced in a follow-up PR.
> style(binding-netconf): resolve linting issues

- examples/templates/exposed-thing/package.json
- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/examples/package.json
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
update to latest "wot-typescript-definition" ( version 21) 
and use "pinned" versions to avoid subtle side effects when minor breaking changes are introduced in a patched version.
> chore: update wot-typescript-definition

- packages/binding-websockets/src/ws-server.ts
Starting from #543 we introduced a new API for the `ExposedThing` this PR aligns the WebSocket server implementation with it. It contains also minor refactorings.
> Allign websocket server with the new `ExposedThing` methods

- examples/browser/counter.js
- examples/scripts/counter.js
- package-lock.json
- package.json
- packages/binding-http/src/http-client.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/oauth-manager.ts
- packages/binding-http/src/subscription-protocols.ts
- packages/browser-bundle/package.json
- packages/core/src/helpers.ts
- packages/core/src/protocol-helpers.ts
This PR introduces back the browser bundle among the supported packages. A couple of notes:
1. I discovered that `node-fetch` when used in browsers defaults to native `fetch` implementation this means the http client was sending `ReadableStreams` (instead of `Readable` from NodeJS) instance to the core. The core is expecting that every binding respect the contract of the `Content` interface which requires a NodeJS `Readable`. This PR changes `binding-http` to convert the stream before sending it the the `core`
2. `browserify` is using an old package for replacing nodejs `url` package. This creates issues when directly importing `url`. I discovered that using the global `URL` variable bypass `browserify` and it works well in browsers too. This PRs adds this workaround. Maybe #640 is …
> Fix browser example

- README.md
I recently struggled over a problem with having an NPM v 6 on an older machine.
Unfortunately the error log wasn't very clear what was causing the issue.
Hence I suggest to add this note about minimum npm requirement also.
> add minimum npm version as requirement

- .eslintrc.js
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/test/http-client-oauth-tests.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-mbus/src/mbus-connection.ts
- packages/binding-modbus/src/modbus-connection.ts
- packages/cli/src/cli-default-servient.ts
- packages/cli/src/cli.ts
- packages/core/src/consumed-thing.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/wot-impl.ts
- packages/core/test/ClientTest.ts
- packages/examples/src/scripts/counter-client.ts
- packages/examples/src/scripts/smart-coffee-machine-client.ts
- packages/examples/src/scripts/smart-coffee-machine.ts
- packages/td-tools/src/td-parser.ts
- packages/td-tools/src/thing-description.ts
This PR should resolve the first point of #534. The typescript-specific rule `@typescript-eslint/no-use-before-define` is added as an replacement for `no-use-before-define` which gets rid of some false positives. In the remaining cases, the issues are resolved by reordering definitions so that they are only used after they have been introduced.
> Solve Eslint issues with circular definitions

- package-lock.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/examples/src/security/oauth/exposer.ts
- packages/td-tools/package.json
This PR resolves another eslint issue by updating the `wot-thing-description-types` dependency and removing the `@ts-ignore` comment from the OAuth2 exposer example.
> fix(examples): fix oauth2 exposer example

- .github/workflows/ci.yaml
As all eslint errors have now been fixed, we can actually let the CI fail if there should be any linting errors, asserting better code quality :)
> chore: let CI fail on linting error

- packages/binding-firestore/.eslintrc.json
- packages/binding-firestore/package.json
- packages/binding-firestore/src/codecs/firestore-codec.ts
- packages/binding-firestore/src/firestore-client.ts
- packages/binding-firestore/src/firestore-handler.ts
- packages/binding-firestore/src/firestore-server.ts
- packages/binding-firestore/test/firestore-client-basic-test.ts
- packages/binding-firestore/test/test-thing.ts
This PR makes a first couple of changes to the Firestore binding to be able to perform eslint checks in the CI. A number of type definitions are labelled as `any` for now as there seemed to be no Firestore typings, yet. These warnings should be addressed in a follow-up PR.
> style: fix eslint errors in Firestore binding

- utils/check_package_version_consistency.js
because  "examples/servients" doesn't exist anymore
> chore(main): fix check:versions

- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-netconf/src/netconf.ts
- packages/binding-netconf/src/xpath2json.ts
- packages/binding-netconf/test/netconf-client-test.ts
This PR applies some refactorings to the netconf binding, resolving a number of eslint warnings. There are now six warnings remaining in the `netconf-codec.ts` and the `xpath2json.ts` files which seem to require more substantial changes/type checking to be fixed. These should probably be dealt with in a follow-up PR.
> style(binding-netconf): address linting issues

- packages/core/src/helpers.ts
As the title says this PR does a minor fix in the fetch function. Previously the client was closed before reading the stream and this causes some unexpected crashes.
> fix(core): closing client after readStream in fetch

- package-lock.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/cli/src/cli-default-servient.ts
- packages/cli/test/RuntimeTest.ts
- packages/cli/test/tsconfig.json
- packages/core/package.json
- packages/core/src/servient.ts
Being close to our big release I thought that it makes sense to improve node-wot architecture with this substantial refactor. This PR moves the VM dependence from `core` to `cli`. The direct consequence of this change is that now the `core` module is leaner and it has not node only dependencies. Moreover, we can better serve users that want to use node-wot as a simple library (embedded in their applications) cause in 99% of cases they don't need the scripting runtime support. 
Fix #377
> Move vm from core to cli package

- packages/cli/src/cli.ts
This PR introduces a new cmd line option to pass the port and override default configurations (or the config file). Furthermore, it improves a little bit the `cli.ts` style code. 
Fix #117
> CLI: pass port as argument

- package-lock.json
- packages/binding-http/package.json
- packages/binding-http/src/codecs/tuya-codec.ts
- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-client.ts
- packages/binding-http/src/http.ts
- packages/binding-http/test/credential-test.ts
Hello everyone,
I've developed a "binding" (codec + credential class) that allows Node-Wot to interact with Tuya's smart things.  
The binding is only client-side and it needs a slightly custom TD in order to work: a custom field ("tuya:PropertyName") in the schema that corresponds to the name used by tuya Apis to identify the property and two different forms for reading and writing (with an Url formed this way: https://openapi.{tuyaRegion}.com/v1.0/iot-03/devices/{deviceID} as a base Uri + /status (read) + /commands (write)).
The credential class implements the custom security protocol used by tuya Apis, it is a bit complicated and it needs a lot of data: it uses a secret key to sign a header field composed of the public key from tuya, a token, the current time, the method an ashed body …
> added tuya binding with security and codec management

- packages/binding-firestore/test/firestore-client-basic-test.ts
I looked into the cause of the test failure but could not find a clear cause.
I did not reproduce the same phenomenon in my environment.
Here are some notes on what I found out.
* The test code requested the Firestore emulator to retrieve data, but no response seems to have been returned
* I'm not sure if this is related, but one test before the failure I was getting the following error  
[2022-05-13T06:26:56.981Z]  @firebase/firestore: Firestore (9.7.0): FIRESTORE (9.7.0) INTERNAL ASSERTION FAILED: Unexpected state
* The above error was reported to be caused by jest, but I do not know the cause because we are not using jest this time
I have removed the failing before each method for now and combined it with the before method.
If the problem was caused by repeated initialization …
> issue-755 Measures for binding-firebase test failure

- package-lock.json
- packages/binding-coap/package.json
This PR updates node-coap, incorporating a number of small fixes regarding the observe function, which were responsible for some hanging behavior. These issues should now be resolved for good :)
> chore: update coap to version 1.0.11

- README.md
- examples/templates/exposed-thing/package.json
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore-browser-bundle/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
set/fix TS definitions to
- "wot-thing-description-types": "1.1.0-09-February-2022"
- "wot-thing-model-types": "1.1.0-3-February-2022"
> chore: increase version to 0.8.2 and fix TD&TM dependency issues

- packages/core/src/codecs/json-codec.ts
- packages/core/src/codecs/netconf-codec.ts
The json codec returned the value corresponding to the key "value" of the readed property, instead of the full json object as expected and described in the TD.
Signed-off-by: MartinMeyer1 <meyer.mart@outlook.com>
> fix: return the object as described in the TD

- packages/core/src/consumed-thing.ts
Notice that I've tried to add a test for this change but the current test suite is at a very high abstraction level. At that level, the bug is negligible since if you provide 0 as formIndex the code will end up choosing the first form anyway. Unless the first form contains a form that has a client but in this case, the operation will fail anyway.
> Strictly check for undefined in getClientFor

- packages/core/src/exposed-thing.ts
- packages/core/src/protocol-listener-registry.ts
- packages/core/test/ProtocolListnerRegistryTest.ts
This PR improves the code structure by delegating the process to notify protocol bindings to a dedicated class: `ProtocolListenerRegistry`. This simplifies the code inside `ExposedThing` and makes it more readable. The PR also comes with additional tests to improve the code coverage. 
Side effects:
- It also refactors the `ExposedThing.destroy` method to use async and await. 
- Fixes #778
> Refactor event handling in exposed thing

- README.md
- packages/cli/README.md
I am moving CLI readme to its own package's readme and thus tidying up the main one. 
I have started in the web editor but it is not easy to check for prettier etc.
> Reorganising CLI Readme information

- packages/binding-http/package.json
- packages/binding-http/src/http-server.ts
- packages/binding-mqtt/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/core/src/exposed-thing.ts
- packages/examples/package.json
- packages/td-tools/package.json
- packages/td-tools/src/td-helpers.ts
- packages/td-tools/src/td-parser.ts
- packages/td-tools/test/TDParseTest.ts
Note: I am sometimes **VERY** surprised how _unrelated_ changes (see https://github.com/w3c/wot-scripting-api/commit/8c73b707462b494787d2d261e8f09b7d70dadcfc) break the types (`@context/@language`) used in node-wot.
Does anyone know why? Kind of frustrating.
> Update npm wot thing description types 2022 07 13

- packages/browser-bundle/build.js
Sorry, it seems that when I cleaned up the `built.js` script I wrongly assigned the list of builtins to the root configuration object of browserify. Silly mistake. Now everything should work correctly on the browsers. 
fixes https://github.com/eclipse/thingweb.node-wot/issues/785
> Correctly configure built-ins in browserify

- packages/binding-firestore/README.md
- packages/binding-firestore/src/firestore-client-factory.ts
- packages/binding-firestore/src/firestore-client.ts
- packages/binding-firestore/src/firestore-handler.ts
- packages/binding-firestore/src/firestore-server.ts
- packages/binding-firestore/test/firestore-client-basic-test.ts
- packages/binding-firestore/test/test-thing.ts
- packages/examples/src/bindings/firestore/README.md
- packages/examples/src/bindings/firestore/counter-client.js
- packages/examples/src/bindings/firestore/counter-thing.js
I was able to deal with it only by modifying the test, example code and README.
> Support observeProperty in binding-firestore

- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/test/http-server-test.ts
- packages/examples/src/bindings/http/example-server.ts
This is a proof of concept to introduce URL rewrite capabilities in node-wot (i.e., using a desired URL for a given resource);
urlRewrite takes precedence and rewrites any possible "input" URL.
I tried to keep the changes as minimal as possible.
Moreover, I modified an example to show how this might look like in practice. You can run and play with it of course.
Questions/Downsides:
* One needs to know the *internals* of node-wot to know to which URL to point to.
(e.g,. `"/myroot/foo/cnt"`  -->  `"/mycounter/properties/count"`)
* The ThingDescription itself contains the actual URL. Do we need to update the TD as well? What if multiple URLs point to the same resource?
* We do not differ between GET/PUT/POST request. Do we need to do so?
TODOs
* update …
> URL rewrite

- .github/workflows/ci.yaml
This morning I read a Twitter thread from @mcollina, about caching node:_modules to speed up CI runs. Since our runs last already an eternity I think we can try this minor tweak. Let's see if it improves the situation. :)
> chore: use cache in CI

- packages/cli/src/cli.ts
- packages/cli/src/wot-servient-schema.conf.json
Note: left out serverKey, serverCert, and security
fixes https://github.com/eclipse/thingweb.node-wot/issues/815
> refactor: add missing HTTP options (address, baseUri, and urlRewrite)

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/test/coap-server-test.ts
Dealing with another CoRE Link-Format implementation, I noticed that I forget the `,` as a delimiter between resources in our current implementation (see, for example, [section 5 of RFC 6690](https://www.rfc-editor.org/rfc/rfc6690#section-5)). This PR provides a simple fix and adjusts the existing test accordingly.
> fix(binding-coap): use correct delimiter for CoRE resources

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-coap/test/coap-server-test.ts
In order to also support the assertion [`exploration-server-coap-size2`](https://w3c.github.io/wot-discovery#exploration-server-coap-size2), this PR adjusts the CoAP binding to be able to include the option in responses. However, there are a couple of bugs which prevent this PR from being complete at the moment, therefore I opened it only as a draft for now.
> feat(binding-coap): add support for Size2 estimate

- CONTRIBUTING.md
- README.md
As raised in #843, this PR updates the README file with information regarding the new logging approach and provides examples for both users and package implementors.
Resolves #843.
> docs: update Logging section in `README` and `CONTRIBUTING.md`

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/test/coap-server-test.ts
- packages/core/src/content-serdes.ts
Dealing a bit more with CoAP content negotiation, I noticed in the [RFC](https://www.rfc-editor.org/rfc/rfc7252#section-5.10.4) that instead of using a default Content-Format in the case of failed negotiation, an error response ~should~ must be sent. This PR takes that into account, adjusting the internal `negotiateContentFormat` method and the test. Since this caused the logic to become a bit more complicated, I added some documentation to hopefully clarify how the new, now RFC-compliant process works.
> fix(binding-coap): send error response if content negotiation fails

- .dockerignore
- Dockerfile
- package.json
This adds the lock file to the build container, to use the expected versions and not let the build process select newer ones.
I believe this is ok, as the container build already selects a fixed build and runtime container tag. So the content of the container should be much more predictable.
This also adds full container names instead of shortnames.
Closes: #870
> Fix the build by locking versions during the container build

- packages/binding-coap/test/coap-server-test.ts
This PR fixes an issue with the current CoAP tests raised by @danielpeintner in https://github.com/eclipse/thingweb.node-wot/pull/878#issuecomment-1326023114. The content negotiation test currently fails due to the fact that `application/foobar` (which was added as an example for an unsupported content type) is not registered in node-coap and therefore throws an error.
In order to resolve this problem, this PR adds a call to the `registerFormat` function and registers `application/foobar` with the reserved numeric value 65000 within the test in question.
> fix(binding-coap): fix content negotiation test

- examples/templates/exposed-thing/package.json
Hi!
I am new to node-wot and wanted to quickly setup a demo with two things. I found the exposed-thing template in the examples folder.
While one can use the example when executing `npm install` and `npm build` from the root directory, copying the example folder and executing the same command within the exposed-thing folder fails for two reasons:
1. `"@node-wot/binding-http": "0.8.3"` and `"@node-wot/core": "0.8.3"` are not published on the npm registry yet. Without installing modules and building from the root of the project, npm fails to load these modules from the registry.
2. `"ajv": "^7.0.4"` breaks the code in `index.js` (importing and using ajv) since the way of importing the library changed from version `^6.12.4` (which is locked in the `package-lock.json` in the root).
I suggest …
> Fixed package.json dependency versions of exposed-thing example

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore-browser-bundle/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
Note: besides the actual version increase I also limited vm2 dependency to "3.9.11" for CLI since latest version "3.9.12" causes build issues
```
node_modules/vm2/index.d.ts:38:40 - error TS1176: Interface declaration cannot have 'implements' clause.
38 export interface VMFileSystemInterface implements VMFS, VMPath {
~~~~~~~~~~
node_modules/vm2/index.d.ts:46:14 - error TS2420: Class 'VMFileSystem' incorrectly implements interface 'VMFileSystemInterface'.
Property 'isSeparator' is missing in type 'VMFileSystem' but required in type 'VMFileSystemInterface'.
46 export class VMFileSystem implements VMFileSystemInterface {
~~~~~~~~~~~~
node_modules/vm2/index.d.ts:40:2
40  isSeparator(char: string): boolean;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
'isSeparator' is declared here.
```
> chore: increase dev version to 0.8.4

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
This PR implements a simple content negotiation mechanism for the HTTP binding and adds two ~an~ additional tests. In the process, I applied some refactoring to the language negotiation code.
> feat(http-server): implement TD content negotiation

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap.ts
- packages/binding-coap/src/coaps-client.ts
- packages/binding-coap/test/coap-client-test.ts
- packages/binding-coap/test/coap-types-test.ts
This PR implements a first version of the [CoAP Binding-Template](https://w3c.github.io/wot-binding-templates/bindings/protocols/coap/index.html) in the `binding-coap` package. While all current vocabulary terms are included, not all of them are handled yet (especially the qblockwise and hop-limit parameters).
Due to the changed prefix and a new vocabulary term for the methods, this PR should actually constitute a breaking change. Therefore, it might be included in the 0.9.0 release?
> feat(binding-coap)!: use new binding-template

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
This PR should resolve https://github.com/eclipse/thingweb.node-wot/issues/905. I already tested the examples in the browser and they are working again :) I will also another test case so that this is also asserted by the CI.
> fix(binding-http): fix content negotiation

- packages/binding-modbus/src/modbus-client-factory.ts
As discussed in #904, with the Modbus client caching should happen per `Servient` as multiple connections to the same ModbusTCP network will cause collisions. For this reason in the issue, I discussed the possibility to cache clients in a global manner, but when I was starting to implement I figured out that this feature is already there! we have a factory. Therefore, for Modbus, I simply implement a singleton and should work for most of the use cases. With this change, one Servient will have only one instance of the `ModbusClient`, that will manage the dispatch of requests to multiple hosts. It also manages connections and, consequently, can serialize multiple requests to one single host.
> Use singleton pattern in the Modbus client factory

- packages/binding-coap/test/coap-client-test.ts
- packages/binding-coap/test/coap-server-test.ts
- packages/binding-http/test/credential-test.ts
- packages/binding-http/test/http-client-basic-test.ts
- packages/binding-http/test/http-client-oauth-tests.ts
- packages/binding-http/test/memory-model.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/binding-mbus/test/test-servient.ts
- packages/binding-modbus/src/modbus-client-factory.ts
- packages/binding-modbus/test/modbus-client-test.ts
- packages/binding-modbus/test/modbus-connection-test.ts
- packages/binding-modbus/test/test-modbus-server.ts
- packages/binding-modbus/test/test-servient.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.integration.ts
- packages/binding-netconf/test/netconf-client-test.ts
- packages/binding-opcua/test/client-test.ts
- packages/binding-opcua/test/fixture/basic-opcua-server.ts
- packages/binding-opcua/test/full-opcua-thing-test.ts
- packages/binding-opcua/test/opcua-codec-test.ts
- packages/binding-opcua/test/schema-validation-test.ts
- packages/binding-websockets/test/ws-tests.ts
- packages/cli/test/RuntimeTest.ts
- packages/core/test/ClientTest.ts
- packages/core/test/HelpersTest.ts
- packages/core/test/InteractionOutputTest.ts
- packages/core/test/ProtocolHelpersStreamTest.ts
- packages/core/test/ProtocolHelpersTest.ts
- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- utils/fix-copyright/CopyrightFix.java
The copyright tool did not look into test folder.
I think we should update the year IF the copyright header is there. Having said that, I don't think test files need the header at all.
Since we missed to do that in the past future copyright runs will update the year to 2023 (since this commit will land in 2023)
:-(
> chore: fix copyright year based on last update

- packages/binding-netconf/test/netconf-client-test.ts
Note: I stumbled over "outer describe" when looking at the test log output
> chore: use proper name for netconf client test

- packages/binding-modbus/src/modbus-connection.ts
Easy fix for a minor issue. I found it when I was debugging error messages but I found this one that should be rather simply a generic debug message.
> fix(binding-modbus): use debug log level when closing connection

- packages/binding-modbus/README.md
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus.ts
- packages/binding-modbus/test/modbus-client-test.ts
As the title states this simple PR changes the URL template declared in the Modbus binding to be aligned with https://w3c.github.io/wot-binding-templates/bindings/protocols/modbus/index.html#url. Tests were updated and improved.
> Allign URL template for modbus client

- packages/binding-mbus/README.md
- packages/binding-modbus/README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/919
> docs: remove outdated links to examples/servients

- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/src/modbus.ts
- packages/binding-modbus/test/modbus-client-test.ts
- packages/binding-modbus/test/modbus-connection-test.ts
- packages/core/src/codecs/octetstream-codec.ts
- packages/core/src/protocol-interfaces.ts
- packages/core/test/ContentSerdesTest.ts
This PR mainly fixes #903, but it adds a bunch of other changes aimed to improve raw encoding and decoding. Since there are some refactor commits I suggest to start reviewing from start to end using this agenda:
- ecd0107defbc2e2fc8337cbaf78b3f645ad4abb5: is the main change. Here I remove the logic of handling endianess in the modbus client and moved it to the core codecs. 
- 5f67eb4304c4a66b06b8f1df8244f666a8137231: while debugging I found out that Buffer.toString() does not print the nice output you can see from `console.log(buff) // prints <Buf 0x2e 0xc5>`. Now the buffer is printed correctly plus some other information about the parameters used while decoding the value. 
- fc72c1ed2b3b0cec79a2d921e18c2af2a0bfd27e while I was at it I refactored the two main parsing functions of the …
> Move endianness from binding-modbus to core

- package-lock.json
- packages/binding-http/package.json
- packages/binding-http/test/http-client-oauth-tests.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/memory-model.ts
- packages/binding-modbus/test/modbus-client-test.ts
- packages/binding-modbus/test/modbus-connection-test.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.integration.ts
I did some improvements in our test suites hoping to reduce wasted time while developing with node-wot. With the reference to #831, the situation is improved but it is not perfect. Some caveats:
- fake timers do not work with sockets ( I went deep down inside node.js internals and I figured out that they are not using the usual `setTimeout` or equivalent method but rather an internal version. Mocking the `Socket.setTimeout` method does not work either -> I gave up). This still causes some slowness in the Modbus protocol binding.
- mbus still times out at 2sec even if you set another timeout
- OPC-UA is still quite slow. 
In general I think we should save about 5 seconds or more each run.
> Improve test timing

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
This pull request is made to support asset-interface-description.ts functionality by adding a feature that reflects data types of AID datapoints in the converted TD.
> feat: add support for AID's interfaceMetadata datatype conversion to TD's type

- packages/binding-http/src/http-server.ts
- packages/core/src/consumed-thing.ts
Hi, currently the `thing.observeProperty` was not working on the browser and server for the http binding.
- the HEAD header was not supported so I add it
- calling `.stop()` on the returned Subscription was not working. It came from the fact that the Client was not recycled and was generated each time by the Servient. => I'm not totally sure of this fix as it touches pretty abstract code.
Reviews are welcome
> fix http client and server property "subscription"

- packages/binding-http/src/http-server.ts
Fixes #933 by extending the `respondUnallowedMethod` function and setting CORS headers differently in case there is a security scheme other than NoSec.
> Cors with credentials fix

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap.ts
This PR incorporates the changes made in https://github.com/w3c/wot-binding-templates/pull/259 into the CoAP binding implementation.
> feat(binding-coap)!: use blockSize instead of blockSZX

- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.unit.ts
Fixes #942 (more explanations about the adopted solution on the commit messages).
> Fix subscribe unsubscribe and then subscribe again MQTT issue

- examples/security/oauth/exposer.js
- packages/examples/src/security/oauth/exposer.ts
The assertions at https://w3c.github.io/wot-thing-description/#td-security-oauth2-client-flow were being violated
> fix(examples): remove auth server from oauth2 examples

- packages/binding-coap/src/coap-server.ts
In the context of #963. I noticed that the `CoapServer`'s `destroy` method could use some cleanup. This PR refactors the method a bit, using `async/await` instead of a `Promise`, making the code a bit more readable.
There are other places like these elsewhere in the code, I will try to do some further cleanup when I'll continue working on #963 and issues like #982.
> refactor(binding-coap): refactor server's destroy method

- packages/binding-http/test/http-server-test.ts
- packages/core/src/codecs/text-codec.ts
- packages/core/src/content-serdes.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/965
> fix: report SVG values without quotes

- packages/binding-mqtt/src/mqtt-broker-server.ts
> fix(binding-mqtt): fix sending plain value instead of content object

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/mdns-introducer.ts
This PR adds DNS-SD functionality (via mDNS) to the `binding-coap` package in order to cover the respective [assertion](https://w3c.github.io/wot-discovery/#introduction-dns-sd-service-name-udp) from the Discovery specification.
I still need to do some interoperability testing, therefore I opened this PR only as a draft for now. However, hopefully the PR will be ready for review soon :)
> feat(binding-coap): implement DNS-SD via mDNS

- .github/workflows/ci-full.yaml
- .github/workflows/ci.yaml
Note: we can also start "thinking" about removing Node.js 14
> chore: add Node.js 20 and remove Node.js 14 workflow

- examples/browser/counter.js
- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
I noticed that the current web counter-example does not display the images "correctly". I'm not sure if this was something by design or not, but I think it would be better to not display images as simple text like the following:
With this PR the example looks like this:
> fix(examples/counter): correctly display images

- SECURITY.md
see https://www.eclipse.org/projects/handbook/#vulnerability
fixes 
https://github.com/eclipse-thingweb/node-wot/issues/998
> docs: align with Eclipse handbook - Managing and Reporting Vulnerabilities

- .github/workflows/ci-full.yaml
- .github/workflows/ci.yaml
#974 introduced a small syntax error that caused the workflow not to run anymore. This PR provides a simple fix.
> chore(ci): fix syntax error in workflow file, remove Node 20 for now

- examples/templates/exposed-thing/package.json
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/931 also
> chore: update TS definitions (24 May 2023)

- packages/binding-coap/src/coap-server.ts
As pointed out by @egekorkan on Discord, the testthing example currently does not expose forms with CBOR `contentType`s when using a CoAP server. Trying to debug the problem, I noticed that this is caused by the helper functions `updatePropertyFormWithTemplate`, `updateActionFormWithTemplate`, and `updateEventFormWithTemplate`.
After reading through their source code, I am not actually sure what these functions are supposed to do, therefore I simply removed their invocation from the CoAP server for the time being which fixed the problem. If they are necessary to integrate into a server implementation, maybe you could help me out with using them correctly instead, though. Thanks :)
> fix(coap-server): correctly expose additional mediatypes

- packages/binding-http/README.md
- packages/binding-http/src/http-server-middleware.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/test/http-server-test.ts
- packages/cli/README.md
Add a middleware for the http server to handle raw http requests.
An example on how to use the middleware can be found in the tests: https://github.com/Luca8991/node-wot/blob/master/packages/binding-http/test/http-server-test.ts#L53-L101
> feat(binding-http): add http server middleware

- package-lock.json
- packages/binding-http/package.json
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/routes/action.ts
- packages/binding-http/src/routes/common.ts
- packages/binding-http/src/routes/event.ts
- packages/binding-http/src/routes/properties.ts
- packages/binding-http/src/routes/property-observe.ts
- packages/binding-http/src/routes/property.ts
- packages/binding-http/src/routes/thing-description.ts
- packages/binding-http/src/routes/things.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-http/test/http-server-test.ts
Hi all, the goal of this PR is to declutter our HttpServer implementation. Over the years, it got a lot of new functionalities but it never had a second look at its software architecture. My intention was to maintain as much as possible intact the current code base, but also move the logic of handling requests to dedicated functions. Furthermore, as mentioned in the note below this PR introduce a routing library (taken from the well-known library Fastify). This simplified a lot the refactoring with the additional benefit to provide more flexibility in the future. The library is compact, small, and well-supported, so it shouldn't be a problem in the future. 
There are plenty of other changes that I would like to add, but I didn't want to overload the changes shown here. I also spotted some …
> refactor(binding-http/server): introduce routes for each TD endpoint

- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/test/modbus-client-test.ts
small fix: If the href is used to assign the register number, quantity and unitId, this was not processed correctly in the validateAndFillDefaultForm method. The parameters were not taken over into the new result set.
> fix (binding-modbus): Reading Modbus URI design

- packages/binding-coap/src/coap-server.ts
This PR applies some additional refactoring to the `CoapServer` class, removing some nesting from the `handleRequest` method. In follow-up PRs, the logic of this and other methods needs to be further refactored in order to reduce complexity and make the class more maintainable.
> refactor(coap-server): refactor request handling

- packages/binding-http/src/routes/action.ts
- packages/binding-http/test/http-server-test.ts
- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
This PR tackles both problems described in #1041. In particular, now the HTTP server responds using 204 when no content is provided and the payload contains the number zero for the testing ( see 1e7b3fc05d870734ae32249cb7b3df6c8d067dab). 
Fix #1041
> Fix action handling for no contents

- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-client-factory.ts
- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/https-client-factory.ts
- packages/binding-http/src/oauth-manager.ts
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/src/routes/action.ts
- packages/binding-http/src/routes/event.ts
- packages/binding-http/src/routes/properties.ts
- packages/binding-http/src/routes/property-observe.ts
- packages/binding-http/src/routes/property.ts
- packages/binding-http/src/routes/thing-description.ts
- packages/binding-http/src/subscription-protocols.ts
- packages/binding-http/test/credential-test.ts
- packages/binding-http/test/http-client-basic-test.ts
- packages/binding-http/test/http-client-oauth-tests.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-http/test/http-server-test.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/binding-http/tsconfig.json
- packages/core/src/helpers.ts
Yet another big PR, really sorry but I couldn't make it shorter because otherwise, the code base would not even compile. 
relates to #758
> Strict checking for http-binding package

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/coaps-client.ts
- packages/binding-coap/test/coap-client-test.ts
- packages/binding-coap/test/coap-server-test.ts
- packages/binding-coap/tsconfig.json
This PR should tick another box of #758 :)
I noticed only now, though, that I also made a slight API change to the `core` package in the context of this PR. Having another look at it, the change seems reasonable, though. If this PR should only be limited to the `binding-coap` package, then I could also revert the change and find a workaround for the time being.
> chore(binding-coap): use ts strict checking

- packages/binding-modbus/src/modbus-client-factory.ts
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/test/modbus-connection-test.ts
- packages/binding-modbus/test/test-modbus-server.ts
- packages/binding-modbus/tsconfig.json
Yet another down. 
Relates to #758.
> Use ts strict checking for binding modbus

- examples/scripts/countdown.js
- examples/scripts/counter-client.js
- examples/scripts/counter.js
- examples/scripts/smart-coffee-machine-client.js
- examples/security/oauth/consumer.js
- examples/testthing/testclient.js
- packages/core/src/helpers.ts
- packages/examples/src/scripts/countdown.ts
- packages/examples/src/scripts/counter-client.ts
- packages/examples/src/scripts/counter.ts
- packages/examples/src/scripts/smart-coffee-machine-client.ts
- packages/examples/src/security/oauth/consumer.ts
- packages/examples/src/testthing/testclient.ts
- packages/examples/tsconfig.json
relates to https://github.com/eclipse-thingweb/node-wot/issues/758
> strict checking for package examples

- .github/workflows/ci-full.yaml
- .github/workflows/ci.yaml
- README.md
- package-lock.json
- packages/binding-mbus/package.json
This PR updates the node-mbus dependency, incorporating a fix for Node 20, and re-enables the corresponding CI workflow.
Fixes #1004.
> chore(ci): re-enable Node 20

- codecov.yml
see https://docs.codecov.com/docs#tips-and-tricks
fixes https://github.com/eclipse-thingweb/node-wot/issues/1058
> chore: avoid blocking codecov status checks

- packages/binding-mqtt/README.md
The code syntax is wrong and I have removed @hasbel from current list of maintainers
> Fix MQTT Readme

- packages/binding-http/src/routes/property-observe.ts
Fix #1065. We are now using the same policy that we used for events. 
Update: About tests, the current test suite is pretty messy. If you have ideas on how to start testing and better organizing the HTTP server feel free to write a proposal.
> Send headers at connection for HTTP Server observe property

- examples/quickstart/presence-sensor.js
- examples/quickstart/simple-coffee-machine.js
- examples/quickstart/smart-clock.js
- package-lock.json
- packages/binding-mqtt/README.md
- packages/examples/README.md
- packages/examples/package.json
- packages/examples/src/quickstart/README.md
- packages/examples/src/quickstart/presence-sensor.ts
- packages/examples/src/quickstart/simple-coffee-machine.ts
- packages/examples/src/quickstart/smart-clock.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1063
and also addresses https://github.com/w3c/wot-cg/pull/67
It is not done yet since:
> Quickstart Things

- packages/binding-opcua/src/codec.ts
- packages/binding-opcua/src/opcua-protocol-client.ts
- packages/binding-opcua/test/client-test.ts
- packages/binding-opcua/test/full-opcua-thing-test.ts
- packages/binding-opcua/test/opcua-codec-test.ts
- packages/binding-opcua/tsconfig.json
another one of https://github.com/eclipse-thingweb/node-wot/issues/758
Note: since at the moment I am not able to test OPCUA locally due to network/company restriction I will use the CI for testing.
> chore(binding-opcua): enable strict type checking

- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-netconf/src/netconf.ts
- packages/binding-netconf/src/xpath2json.ts
- packages/binding-netconf/tsconfig.json
> chore(binding-netconf): use ts strict checking

- packages/binding-mbus/src/mbus-client.ts
- packages/binding-mbus/src/mbus-connection.ts
- packages/binding-mbus/test/mbus-client-test.ts
- packages/binding-mbus/tsconfig.json
another one of https://github.com/eclipse-thingweb/node-wot/issues/758
@LennyHEVS @Chxresubles can you take a look?
We are enabling strict checking for all node-wot packages
> chore(binding-mbus): enable strict type checking

- examples/quickstart/simple-coffee-machine.js
- examples/quickstart/smart-clock.js
- packages/examples/src/quickstart/simple-coffee-machine.ts
- packages/examples/src/quickstart/smart-clock.ts
[The current deployed Things](http://plugfest.thingweb.io:8081/coffee-machine)http://[plugfest.thingweb.io:8081/coffee-machine](http://plugfest.thingweb.io:8081/coffee-machine) have wrong href due to automatic ip address detection. This fixes it.
With @relu91 we have discussed offline and we should simply move to a dockerized setup to manage all Things and their environment variables (like IP address, port etc.).
> Add static address to quickstart examples

- examples/browser/counter.html
- examples/security/oauth/consumer.js
- examples/security/oauth/wot-server-servient-conf.json
- packages/binding-http/README.md
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/src/routes/action.ts
- packages/binding-http/src/routes/common.ts
- packages/binding-http/src/routes/event.ts
- packages/binding-http/src/routes/properties.ts
- packages/binding-http/src/routes/property-observe.ts
- packages/binding-http/src/routes/property.ts
- packages/binding-http/src/routes/thing-description.ts
- packages/binding-http/src/routes/things.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-http/test/http-server-test.ts
- packages/examples/src/bindings/http/example-server-secure.ts
- packages/examples/src/security/oauth/consumer.ts
- packages/examples/src/security/oauth/wot-server-servient-conf.json
This PR improves the exposing process of the `http-server`. In particular, it focuses on the ability to handle multiple security schemes per `http-server` instance. For example, now the `http-server` can be configure to be able to hosts Things without security and Things with basic schemes:
```js
const td1 = { } // automatically filled with nosec scheme
const td2 = {securityDefinitions: { basic: {scheme: "basic"}}, security: "basic" }
await (await WoT.produce(td1)).expose();
await (await WoT.produce(td2)).expose();
// ok 
```
**Note** that this does not mean that now we can use multiple security schemes in the `security` field or the `combo` SecurityScheme`. For multiple security schemas, I think we can avoid implementing that feature, mainly because it is already [deprecated in TD …
> Add supports for multiple security schemes in http server

- examples/quickstart/smart-clock.js
- packages/examples/src/quickstart/smart-clock.ts
> fix(examples/quickstart/smart-clock): change default port

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/test/coap-server-test.ts
- packages/binding-http/src/http-server.ts
- packages/core/src/helpers.ts
> feat(coap-server): add support for URI variables

- packages/binding-netconf/src/async-node-netconf.ts
While working on #1078, I noticed that there is a warning emitted by eslint regarding the use of `!` for non-null-assertions. This PR simply replaces the `!`s with `?` (for optional chaining) which should avoid unwanted errors during runtime if one of the parameters should be undefined.
> fix(binding-netconf): use optional chaining for non-null-assertion

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/coap.ts
- packages/binding-coap/test/coap-client-test.ts
- packages/binding-coap/test/coap-server-test.ts
- packages/cli/src/cli-default-servient.ts
- packages/examples/src/quickstart/smart-clock.ts
As pointed out by @egekorkan in #1028, the CoAP server currently has a different constructor API that differs from its HTTP counterpart.
This PR introduces a `CoapServerConfig` interface that features the previously defined `address` and `port` parameters in order to align it with the HTTP implementation (and probably also other binding implementations). Using this approach will also make it possible to extend the CoAP server more easily in the feature (e.g., with a security configuration).
As this PR introduces a breaking change, however, I suppose merging it should be postponed until the next minor(?) release.
Will resolve #1028.
> feat!(coap-server): adjust constructor to HTTP server

- examples/quickstart/README.md
- examples/quickstart/simple-coffee-machine.js
- packages/examples/src/quickstart/simple-coffee-machine.ts
As discovered in W3C TPAC, we should fix the TD Data Schema otherwise error is returned with property read
> Data Schema Fix for Quickstart example

- packages/binding-coap/src/coap-server.ts
While preparing to implement #1014, I noticed that there is actually some room for simplification in the current CoAP server implementation. This PR makes the corresponding changes, getting rid of two unnecessary helper functions I previously introduced.
> refactor(coap-server): simplify form generation

- packages/binding-coap/.eslintrc.json
- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/tsconfig.json
This PR addresses one of the checkmarks in #1046.
> chore(binding-coap): enable strict-boolean-expressions and null checks

- packages/binding-coap/test/coap-server-test.ts
In the context of #1086 and #1077, I noticed that in the CoAP tests, not all invocations of `coapServer.stop()` are actually explicitly being awaited which might cause the CI to hang if there is an unexpected error.
This PR makes a couple of minor adjustments to improve the cleanup of resources and fix this potential problem (although I am not sure to which extent it is actually a problem to begin).
> test(binding-coap): `await` all calls of `coapServer.stop()`

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/test/coap-server-test.ts
Based on the refactoring made in #1084, this PR adds initial support for meta operations, namely the reading of multiple or all properties, to the CoAP server. This corresponds with issue #1014 – as only one kind of meta operation is supported yet, I think the issue can be kept open for now.
I haven't figured out the correct way to implement writing multiple properties yet, which is why I left it out of this PR for now. However, a method skeleton already exists (at the moment, it simply returns an error response with code `5.01` (Not Implemented)) which can be expanded in a follow-up PR.
As this PR depends on #1084, I will rebase once that PR has been merged to make reviewing a bit easier. Until then, I will keep this PR in draft status.
> feat(coap-server): add initial meta operation support

- CONTRIBUTING.md
Following [this comment](https://github.com/eclipse-thingweb/node-wot/pull/1088#issuecomment-1727706226), I thought it would have been good to have some references for future contributors.
> docs(contributing): add a guide for checking of `undefined` or `null`

- examples/scripts/countdown.js
- examples/scripts/smart-coffee-machine-client.js
- examples/scripts/smart-coffee-machine.js
- packages/examples/.eslintrc.json
- packages/examples/src/scripts/countdown.ts
- packages/examples/src/scripts/smart-coffee-machine-client.ts
- packages/examples/src/scripts/smart-coffee-machine.ts
- packages/examples/tsconfig.json
This PR addresses one checkmark in https://github.com/eclipse-thingweb/node-wot/issues/1046.
> chore(examples): enable eslint/strict-boolean-expressions and strictNullChecks

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- packages/td-tools/test/util/inverterModbus.json
fixes issues with combination of `base` and abolsuteURL in `href `.
Added according (Modbus) test.
> fix(td-tools): proper absoluteURL handling in AAS/AID

- packages/binding-http/test/http-client-basic-test.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/837
> refactor(binding-http): re-introduce proper error message check

- packages/binding-coap/test/coap-server-test.ts
- packages/binding-file/src/file-client.ts
- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/http-server-test.ts
- packages/binding-mbus/src/mbus-client.ts
- packages/binding-mbus/test/test-servient.ts
- packages/binding-modbus/test/test-servient.ts
- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/cli/src/cli-default-servient.ts
- packages/core/test/ClientTest.ts
- packages/core/test/ServerTest.ts
- packages/examples/src/scripts/smart-coffee-machine.ts
This PR contributes to resolving #569. There are a few instances of the `return Promise` pattern left that were a bit difficult to resolve, though, so I am not sure whether we should keep the issue open?
> refactor: remove unnecessary `new Promise` wrappers

- packages/binding-opcua/README.md
Corresponding with #1013, this PR updates the example in the README file for the OPCUA binding, ticking two checkmarks. A more detailed description of how to run the example still needs to be added.
> docs(binding-opcua): fix demo-opcua1.ts in README

- packages/binding-http/src/http-server.ts
- packages/core/src/consumed-thing.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/helpers.ts
JavaScript nowadays has a built-in function for deep-cloning called `structuredClone` which makes it possible to get rid of the `JSON.parse(JSON.stringify(foo))` construction. I found a few places where the new function can be used, hopefully increasing readability and performance a bit.
Cases where the parse-stringify-approach still needs to be used *could* be revisited in the future to arrive at a slightly cleaner implementation.
> refactor: use `structuredClone` for deep copying

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- packages/td-tools/test/util/inverterModbus.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1112
> refactor(td-tools): AID idShort does not allow ":" and uses "_" instead

- packages/binding-http/.eslintrc.json
- packages/binding-http/src/codecs/tuya-codec.ts
- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/src/routes/action.ts
- packages/binding-http/src/routes/common.ts
- packages/binding-http/src/routes/event.ts
- packages/binding-http/src/routes/properties.ts
- packages/binding-http/src/routes/property-observe.ts
- packages/binding-http/src/routes/property.ts
- packages/binding-http/src/routes/thing-description.ts
- packages/binding-http/test/http-client-basic-test.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/http-server-test.ts
- packages/binding-http/test/memory-model.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
Ticks one of the boxes of #1046 :)
> chore(binding-http): enable eslint/strict-boolean-expressions

- packages/binding-opcua/src/codec.ts
see https://github.com/eclipse-thingweb/node-wot/pull/1072
> refactor(binding-opcua): remove unnecessary data transformation

- packages/binding-opcua/test/client-test.ts
- packages/binding-opcua/test/full-opcua-thing-test.ts
see https://github.com/eclipse-thingweb/node-wot/pull/1072
> chore(binding-opcua): improve/stabilize tests

- README.md
Extending the readme with the other online Things we have. For the CG tutorial, we have stored the TDs in Zion and I am doing the same here but we can discuss that if needed. The reason for that was that we needed somewhere to store the MQTT TD. Alternatives could be: 
- Storing the TDs in this GitHub
- Storing them at `domus-directory` when it is here
> Add quick start online Things to README.md

- .eslintrc.js
- packages/binding-http/src/codecs/tuya-codec.ts
- packages/binding-mbus/src/mbus-client.ts
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-opcua/src/opcua-protocol-client.ts
- packages/core/src/codecs/text-codec.ts
- packages/td-tools/src/thing-model-helpers.ts
Actually completely resolves #1092.
> fix: enable prefer-nullish-coalescing eslint rule

- packages/binding-coap/tsconfig.json
- packages/core/tsconfig.json
- packages/examples/tsconfig.json
- packages/td-tools/tsconfig.json
- tsconfig.json
As another step towards resolving #1046, this PR enables `strictNullChecks` globally and removes it from individual packages that extend the global `tsconfig.json` file.
> chore: enable strictNullChecks globally

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- packages/td-tools/test/util/inverterModbus.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1128
> feat: support special AID treatment for ranges

- .eslintrc.js
- packages/binding-coap/.eslintrc.json
- packages/binding-file/src/file-client.ts
- packages/binding-http/.eslintrc.json
- packages/binding-mbus/src/mbus-client.ts
- packages/binding-mbus/src/mbus-connection.ts
- packages/binding-mbus/test/mbus-client-test.ts
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.integration.ts
- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-netconf/src/netconf.ts
- packages/binding-netconf/src/xpath2json.ts
- packages/binding-opcua/src/factory.ts
- packages/binding-opcua/src/opcua-protocol-client.ts
- packages/binding-opcua/test/client-test.ts
- packages/binding-opcua/test/fixture/basic-opcua-server.ts
- packages/binding-websockets/src/ws-server.ts
- packages/cli/src/cli-default-servient.ts
- packages/cli/src/cli.ts
- packages/core/.eslintrc.json
- packages/examples/.eslintrc.json
- packages/td-tools/.eslintrc.json
Depends on #1126, resolves #1046.
> refactor: enable strict-boolean-expressions globally

- .github/workflows/ci.yaml
This might require some discussion/fine-tuning, but since some of our tests are currently hanging for a long time on a regular basis before they are eventually canceled (after reaching the maximum of six hours), this PR proposes limiting the actual testing step to a maximum of five minutes, so that the CI workflow is aborted much earlier than it is now.
I chose five minutes for now because in general, the testing step seems to take about three minutes at maximum, but we could also consider setting it to a higher value – I guess anything lower than `360` would already be an improvement 😅
I think a change like this will also be good for receiving feedback on failed tests much earlier than is currently the case, as any failing test present in a PR might cause this behavior.
> ci: set a timeout for testing step of ten minutes

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
description, contentMediaType, const, default, and unit
> refactor(td-tools): add support for more TD dataSchema terms

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
e.g., "+" is not allowed
fixes https://github.com/eclipse-thingweb/node-wot/issues/1145
> fix(td-tools/AID): use valid idShort for AID

- .vscode/launch.json
- packages/cli/src/cli-default-servient.ts
- packages/core/src/exposed-thing.ts
Note: reverts parts of https://github.com/eclipse-thingweb/node-wot/pull/1105
fixes https://github.com/eclipse-thingweb/node-wot/issues/1151
> refactor: revert back to *old* way of cloning

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1148
> refactor(AID): report proper valueType for value

- .github/workflows/ci.yaml
fixes https://github.com/eclipse-thingweb/node-wot/issues/1154
> fix: resolve GitHub runner issues on MacOs

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: Every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
Hence on can see many changes for `package-lock.json` ...
> chore: increase version numbers to 0.8.11 for next release

- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/core/src/wot-impl.ts
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
- wot-typescript-definitions@0.8.0-SNAPSHOT.29
- wot-thing-description-types@1.1.0-09-November-2023
- wot-thing-model-types@1.1.0-09-November-2023
Note:  adds _empty_ discovery methods:
- `discover(...)`
- `exploreDirectory(...)`
- `requestThingDescription(...)`
> chore: update Scripting API and TD/TM NPM versions

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1163
> refactor(td-tools/AID): add required AID terms (if missing) based on op

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1161
> refactor(td-tools/AID): add semanticId to forms

- README.md
Testing out #1166 with adjusted versions of the examples from the README file, I noticed that there is a small error in the client example. This PR resolves the issue.
> docs(README): use correct variable name in client example

- packages/binding-coap/src/coap-client.ts
- packages/binding-coap/src/coaps-client.ts
- packages/binding-file/src/file-client.ts
- packages/binding-http/src/http-client-impl.ts
- packages/binding-mbus/src/mbus-client.ts
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-opcua/src/opcua-protocol-client.ts
- packages/binding-websockets/src/ws-client.ts
- packages/core/src/protocol-interfaces.ts
- packages/core/src/wot-impl.ts
- packages/core/test/ClientTest.ts
This PR adds an initial implementation for the `requestThingDescription` method.
The implementation details probably still need some additional discussion – looking forward to your feedback here :) For now, I extended the `ProtocolClient` interface with a new `requestThingDescription` method that is expected to return a `Content` object that is deserialized and (supposed to be ) validated by the `WoT` implementation.
I think this latter part also touches #1055 – in my opinion, there should be some validation happening so that library users can be sure that they always receive a valid Thing Description. Maybe the algorithm(s) in the Scripting API would need to be adjusted then as well.
For now, I only implemented the protocol-specific `requestThingDescription` method for HTTP and CoAP, if …
> feat: add initial requestThingDescription implementation

- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/test/modbus-connection-test.ts
If we don't clean up the queue and the application is looping trying to read Modbus registers, the queue will grow indefinitely. This cleans up the queue when a timeout occurs (e.g. wrong remote host or not reachable).
> fix(binding-modbus): clean up operations when timeout

- .github/workflows/ci.yaml
In the context of #1175, I noticed that the codecov step was somehow hanging for over 2 hours without causing the CI to fail. To address the issue, this PR proposes to add an additional "total" timeout value of 30 minutes for the whole job which should be enough to cover all runs that work as intended.
> ci: add a total timeout of 30 minutes

- API.md
- README.md
- examples/scripts/counter-client.js
- examples/scripts/smart-coffee-machine-client.js
- examples/security/oauth/consumer.js
- examples/testthing/testclient.js
- packages/binding-coap/README.md
- packages/binding-http/README.md
- packages/examples/src/bindings/coap/example-client.ts
- packages/examples/src/bindings/http/example-client.ts
- packages/examples/src/scripts/counter-client.ts
- packages/examples/src/scripts/smart-coffee-machine-client.ts
- packages/examples/src/security/oauth/consumer.ts
- packages/examples/src/testthing/testclient.ts
I think we should use `requestThingDescription()` instead of the generic `fetch()` everywhere.
Please let me know whether this change makes sense. 
fixes https://github.com/eclipse-thingweb/node-wot/issues/1055
> refactor: favor WoT.requestThingDescription instead of general fetch

- packages/binding-coap/src/coap-server.ts
Resolves #1182.
This is more like a workaround for now to fix the crashes immediately but should be fixed at the library level eventually.
> fix(coap-server): ignore incoming requests with an invalid source port

- .github/workflows/ci.yaml
This PR introduces a retry mechanism with enabled debug logging for failed CI testing steps as discussed in https://github.com/eclipse-thingweb/node-wot/pull/1184#issuecomment-1845510736.
> ci: re-run failed test steps with debug logging enabled

- package-lock.json
- packages/binding-file/test/test2.txt
- packages/binding-mqtt/package.json
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-mqtt/src/mqtt-client.ts
- packages/binding-mqtt/src/mqtt-message-pool.ts
- packages/binding-mqtt/src/mqtt.ts
- packages/binding-mqtt/src/util.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.integration.ts
- packages/binding-mqtt/test/mqtt-client-subscribe-test.unit.ts
Given the latest problems that MQTT gave, I tried to revamp it a little bit the implementation in the hope that it would cause fewer problems and would be more maintainable. I took three steps:
- Upgrade the library to the latest MQTT implementation -> we get `async` methods -> cleaner implementation and cover corner cases where we forgot to use callbacks. 
- While I was there I updated the notation with the latest MQTT vocabulary
- I tried to tackle the issue raised in #955 by @ilovemilk . Now it should be fixed but give the current design of the Scripting API (and node-wot). the implementation is not that clean. I refer to the fact that we can't keep track of each listener by using functions as handlers but we use forms as identifiers. The end result is that if in your thing description …
> Generic MQTT improvements

- packages/binding-mqtt/src/util.ts
This is an extremely trivial PR that gets rid of the single warning eslint is currently reporting on the `master` branch.
Since the change is so simple, I will merge it right away.
> chore(binding-mqtt): remove unused debug import

- packages/core/src/content-serdes.ts
- packages/core/src/helpers.ts
- packages/core/src/validation.ts
- packages/core/src/wot-impl.ts
- packages/core/test/DiscoveryTest.ts
This PR starts implementing the `exploreDirectory` method that has recently been added to the Scripting API specification.
> feat(core): implement `exploreDirectory` method

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: Every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
> chore: increase version numbers to 0.8.12 for next release

- .github/workflows/ci.yaml
In the menu for rerunning failed actions, I noticed that there is an option for "enabling debug logging" as can be seen in this screenshot:
Although we have introduced automatic reruns with debug logging in #1189, I got the impression that this change is not that well usable in practice, partly because it makes the logs for failed actions very long, thereby increasing the difficulty of finding the place where something went wrong.
This PR proposes using debug logging only when it is enabled via the GitHub actions UI that can be seen above, making the choice of seeing the verbose output a bit more deliberate. This change would also half the wait time for feedback on a failed test while getting rid of the external dependency introduced for retrying the tests automatically.
> ci: enable logging only when debug logging is enabled

- packages/core/README.md
I've added descriptions for the content type parameters and data schema terms of the `octet-stream` codec, and an example of how to describe an object with the new terms.
(related issue: https://github.com/eclipse-thingweb/node-wot/issues/1194)
> Follow-up octet-stream codec - short explanation #1194

- packages/core/src/interaction-output.ts
While dealing with the `InteractionOutput` class, I noticed that a small bug (due to the `!= null` check) was introduced that prevents already `parsedValue`s of type `null` from being properly returned. This PR solves the issue by replacing the check with `!== undefined`, so that `null` values are not being ignored anymore.
> fix(interaction-output): adjust storing behavior and return type of `value` method

- packages/binding-file/src/file-client.ts
- packages/binding-file/test/.gitignore
This PR tries to make the file-client implementation more reliable by replacing the synchronous `fs` code with asynchronous alternatives from `fs/promises`. I am not sure how much of a difference this will make, but I hope this change will resolve the issues we have been observing since the merging of https://github.com/eclipse-thingweb/node-wot/pull/1175.
> fix(binding-file): improve file-client implementation

- packages/binding-coap/test/coap-server-test.ts
This PR contains a potential fix for the CoAP server problems observed in #1195. As the servients are not used by the `CoapServer` class, I simply removed the invocations of `shutdown` to fix the issue at hand.
In general, I think we could discuss if passing the servient to the protocol interface implementations is actually necessary or if the passing of protocol-specific callbacks for retrieving credentials could be an alternative (this is the approach I used for dart_wot in the meantime). But I would open a dedicated issue for that later :)
> test(coap-server): don't shutdown servient unnecessarily

- packages/core/src/servient.ts
I think it should **not** be possible to start a servient multiple times. Hence I added a simple check.
Moreover, I _think_ a servient should be usable only once. Hence after a `shuthown` it is no longer usable.
Anyhow, I am open to other opinions whether we should allow for a re-`start` again?
fixes https://github.com/eclipse-thingweb/node-wot/issues/1193
> refactor: avoid starting servient multiple times

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/util.ts
- packages/binding-coap/test/coap-server-test.ts
Trying to interact with a test thing using CoAP, I noticed that the forms provided in the Thing Descriptions do not include the `subprotocol` value `cov:observe` for observable properties and events. This PR tries to fix the issue by adding logic to determine if a `subprotocol` should be added to a form.
The implementation got a bit more complicated than initially expected because I noticed that you probably should not simply add the subprotocol to all property forms, but only those containing the op values `observeproperty` and/or `unobserveproperty`. Furthermore, I got the feeling that you should not use `cov:observe` with `readproperty` or `writeproperty` (which I think is currently not clearly stated in the CoAP Binding Template).
Therefore, during the TD generation process, I split …
> fix(coap-server): add missing cov:observe subprotocol

- packages/binding-http/test/http-server-test.ts
- packages/binding-opcua/test/full-opcua-thing-test.ts
- packages/core/src/interaction-output.ts
- packages/core/src/wot-impl.ts
- packages/core/test/DiscoveryTest.ts
As discussed in #1216, the current implementation of the value function didn't take into account the validation of the DataSchema of the target affordance. This PR fix #1216 but it also introduces some required changes to take into account the new behavior in other places of the codebase. In particular, it updates the `exploreDirectory` method and `ThingDiscoveryProcess` class moving the fetching of the list of ThingDescirption from the method to the async iterator. The main reason for this change is that I figured out that with a DataSchema the `readProperty` would throw before entering even starting the `ThingDiscoveryProcess` which would be strange and violate the contract of the method `exploreDirectory` (errors for the list should be conveyed as errors in the ThingDesscovery object). …
> Align `value` function to Scripting API

- examples/testthing/testthing.js
- packages/examples/src/testthing/testthing.ts
I have noticed some beautification improvements in Test Thing. While at it, I have tried to align everything a bit more such as adding events for all properties. The rest is just adding nice titles and descriptions.
> TestThing fixes

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: Every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
> chore: increase version numbers to 0.8.13 for next release

- examples/quickstart/simple-coffee-machine.js
- packages/examples/src/quickstart/simple-coffee-machine.ts
This is adding events to the simple coffee machine. With @relu91 we will use this in the nodejs conf presentation. There are those return statements added after event emissions since without doing that I was getting an event emission with data `"water""beans"`. Some race condition maybe? It is not an elegant solution but if that is indeed an issue with node-wot (and not my oversight), I would propose to go with this PR and open an issue about it.
> Events for simple coffee machine

- packages/core/src/codecs/octetstream-codec.ts
- packages/core/test/ContentSerdesTest.ts
I noticed that the limits for integer serialization are wrong and corrected them. Additionally, I added test for these limits.
Changes in `octetstream-codec.ts`
- serializing `255` as unsigned integer with 8 bits failed, succeeds now;
- serializing `127` as signed integer with 8 bits failed, succeeds new;
Changes in `ContentSerdesTest.ts`
- added tests verifying that `255` as `uint8`, `127` and `-128` as `int8` succeed
- added tests verifying that `256` and `-1` as`unit8`, `128` and `-129` as `int8` fail
> fix(octet-stream): correct limits for integer serialization and add tests

- packages/core/src/interaction-output.ts
- packages/core/test/InteractionOutputTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1228
> refactor: report undefined for no expected value()

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
Found a bug when exposing things with a `baseURI` defined. I added a failing test to verify the correct behavior and avoid regression.
> fix(binding-http): fill security scheme when baseURI defined

- package-lock.json
- packages/core/package.json
- packages/core/src/consumed-thing.ts
- packages/core/test/ClientTest.ts
e.g., expected "application/json" should deal with "application/json; charset=utf-8"
fixes https://github.com/eclipse-thingweb/node-wot/issues/1250
> refactor: handle also enhanced contentTypes

- packages/core/src/codecs/octetstream-codec.ts
- packages/core/test/ContentSerdesTest.ts
After using the octetstream codec's object serialization and deserialization for a while now, I discovered a bug when handling nested objects:
When serializing values, the object's bit-offset would not be passed on to the nested serialization call.
For example (added to the tests in this PR, too):
Serializing an object like
``` json
{
"flags1": { "flag1": false, "flag2": true },
"flags2": { "flag1": true, "flag2": false },
}
```
with the following DataSchema
```json
{
"type": "object",
"properties": {
"flags1": {
"type": "object",
"properties": {
"flag1": { "type": "boolean", "ex:bitOffset": 3, "ex:bitLength": 1 },
"flag2": { "type": "boolean", "ex:bitOffset": 4, "ex:bitLength": 1 },
},
"ex:bitLength": 8,
},
"flags2": {
"type": "object",
"properties": {
"flag1": { "type": "boolean", …
```
> [octetsream-codec] fix serialization and deserialization of nested objects

- packages/binding-modbus/README.md
- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/src/modbus.ts
- packages/binding-modbus/test/modbus-client-test.ts
- packages/binding-modbus/test/modbus-connection-test.ts
Fixes #1234 and #1168 (when the PR is ready ofc).
> Modbus binding alignment

- .github/workflows/ci.yaml
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: As usual, every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
> chore: increase version numbers to 0.8.14 for next release

- packages/core/src/interaction-output.ts
to avoid memory leak
tackles the first easy step of https://github.com/eclipse-thingweb/node-wot/issues/1062
> refactor: avoid adding schemas to AJV

- packages/binding-http/src/http-server.ts
- packages/binding-opcua/test/opcua-codec-test.ts
- packages/binding-opcua/test/schema-validation-test.ts
- packages/core/src/consumed-thing.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/helpers.ts
- packages/core/src/servient.ts
point all functions to it so that in future we can easily update
fixes https://github.com/eclipse-thingweb/node-wot/issues/1252
> refactor: create helper function structuredClone and use *old* way

- packages/cli/src/wot-servient-schema.conf.json
Note: the PR also removed the following from "servient"
```
"dependencies": {
"serverKey": ["serverCert"],
"serverCert": ["serverKey"]
}
```
since 
* `dependencies` are now `dependentRequired` and `dependentSchemas`
* and deals with subschemas which we don't use
Am I wrong?
fixes https://github.com/eclipse-thingweb/node-wot/issues/839
> fix(cli): move serverKey and serverCert under http

- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/test/http-client-test.ts
As discussed in #854  this PR adds the default assumptions for the Accept header when interacting with a remote Thing. It also assumes that if the user provides the headers field his choice has preference over the default assumptions.
> Support for default accept header in http client

- packages/binding-http/src/http-client-impl.ts
Giving the discussion in #1281 I added a warning message if the client is falling back to default protocol (longpoll for us). Please let me know if we can improve the logged message or anything else.
> Console warning when no subprotocol is defined in http form

- packages/binding-coap/src/coap-server.ts
Note: interesting that this is not detected automatically... `error` exists as import also...
> fix(coap): wrong error variable name

- packages/core/src/consumed-thing.ts
- packages/core/src/interaction-output.ts
- packages/core/test/ClientTest.ts
- packages/core/test/InteractionOutputTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1278
> refactor: handle "non"-validating output for async actions 

- packages/binding-http/src/subscription-protocols.ts
- packages/binding-http/test/http-client-test.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1294
> fix: SSE data reporting

- .github/workflows/ci.yaml
- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-mbus/package.json
- packages/binding-mbus/test/mbus-client-test.ts
- packages/binding-mbus/test/mbus-connection-test.ts
- packages/binding-modbus/package.json
- packages/binding-modbus/test/test-modbus-server.ts
This PR combines some of the changes also present in the PRs #1297 and #1274 to partially resolve the failing tests we are currently experiencing by upgrading some of the dependencies and skipping the Mbus tests in the CI under Windows. It also adds Node 22 to the CI matrix.
If this PR should get merged, we should probably create a follow-up issue for continuing the work on resolving the Mbus problem.
Closes #1297, closes #1274, closes #1292.
> Upgrade dependencies, skip mbus tests under Windows, use Node 22 in CI

- .eslintrc.js
- packages/binding-coap/src/mdns-introducer.ts
- packages/binding-http/src/http-browser.ts
- packages/binding-http/src/routes/thing-description.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-websockets/src/ws-server.ts
- packages/core/src/codecs/netconf-codec.ts
- packages/core/src/codecs/octetstream-codec.ts
- packages/core/src/consumed-thing.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/helpers.ts
- packages/core/src/servient.ts
- packages/td-tools/src/td-parser.ts
- packages/td-tools/src/thing-description.ts
- packages/td-tools/src/thing-model-helpers.ts
- packages/td-tools/test/TDParseTest.ts
(Not only) in the context of #1177, I noticed that some of the for loops use the `for ... in` syntax instead of the `for ... of` syntax. Apparently, the former style is discouraged and not recommended by eslint, for example (see https://eslint.org/docs/latest/rules/guard-for-in).
This PR replaces the code lines in question and enforces the new style by activating the `guard-for-in` eslint rule.
> chore: add `guard-for-in` eslint rule

- packages/td-tools/src/thing-model-helpers.ts
fixes https://github.com/eclipse-thingweb/node-wot/pull/1306
> chore(td-tools): deprecate thing-model-helpers' exports

- packages/core/src/interaction-output.ts
- packages/core/test/InteractionOutputTest.ts
As discussed in #1243 and solved in https://github.com/w3c/wot-scripting-api/pull/534, we now allow more root schema types to be accepted in the value function. The validation still happens but it supports: `const`, `enum`, and `oneOf`. Those terms can now be used instead of `type`. The behavior of using these terms **at the same time** is delegated to Ajv.validate function.
> fix(core/interactionOutput): support for no-type based root schemas

- packages/td-tools/src/td-helpers.ts
- Removed unused findProtocol and findPort functions
- Closes #1307
> refactor: remove unused findProtocol and findPort functions

- packages/td-tools/src/td-helpers.ts
- packages/td-tools/src/td-parser.ts
What about https://github.com/eclipse-thingweb/node-wot/blob/master/packages/td-tools/src/thing-description.ts
It will continue to live in `core`, right?
> docs: add deprecation message to td-tools

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: As usual, every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
> chore: increase version numbers to 0.8.16 for next release

- packages/binding-coap/src/coap-server.ts
- packages/binding-coap/src/util.ts
- packages/binding-coap/test/coap-server-test.ts
This PR incorporates the recent changes applied to the CoAP Binding Template document in https://github.com/w3c/wot-binding-templates/pull/353, removing the `cov:observe` subprotocol from the TDs that are generated when adding a CoAP server to a servient.
In order to better cover the consumer behavior described in the CoAP binding template (falling back to polling if the server does not support CoAP observe), some more work is needed that might also need to be applied to the underlying CoAP libraries. I will try to cover these aspects soon in a follow-up PR.
> feat(binding-coap): remove cov:observe subprotocol

- package-lock.json
- packages/core/package.json
Note: I used the exact same version for `is-absolute-url` and `url-toolkit` as in https://github.com/eclipse-thingweb/node-wot/blob/f63b72951fa9190ced8126e2f6b4cfe045b148bf/packages/td-tools/package.json#L20-L22 to avoid issues.
fixes https://github.com/eclipse-thingweb/node-wot/issues/1317
> fix: add missing packages for serdes.ts

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: As usual, every time we update the node-wot package versions we also newly create `package-lock.json` to update dependencies.
> chore: increase version numbers to 0.8.17 for next release

- README.md
Once we agree on this, I will replicate it in the other repositories.
> Adopters information in the readme

- package-lock.json
- packages/binding-file/package.json
- packages/binding-mbus/package.json
- packages/binding-netconf/package.json
- packages/core/src/wot-impl.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1331
> refactor: Use interface for WoT.consume()

- README.md
> Remove browsers versions from README.md

- README.md
After https://github.com/eclipse-thingweb/node-wot/pull/1336 it might make sense to list the possible set of tests.
@relu91 do you think this is the right place?
> docs: list different set of tests

- package.json
Incidentally unbreaks `deno install`.
> chore: Simplify the workspaces list

- examples/scripts/countdown.js
- examples/scripts/counter-client.js
- examples/scripts/smart-coffee-machine-client.js
- examples/scripts/smart-coffee-machine.js
- examples/security/oauth/consumer.js
- examples/templates/exposed-thing/tsconfig.json
- packages/examples/tsconfig.json
- tsconfig.json
As explained in #1267 we decided to move to a more modern js target. After #1336 everything goes pretty smooth, I'll double check next week if there is anything more to do (or please just comment below if you know more).
> Move to es2021

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
Minor version change needed due to
https://github.com/eclipse-thingweb/node-wot/pull/1332
> Prepare for next release with new minor version 0.9.0

- package-lock.json
- package.json
- packages/binding-opcua/tsconfig.json
Follow-up for https://github.com/eclipse-thingweb/node-wot/pull/1335
Tackles the following discussions
* no need to duplicate configuration options, see https://github.com/eclipse-thingweb/node-wot/pull/1335#discussion_r1942427717
* revert @types/node version back to v18, see https://github.com/eclipse-thingweb/node-wot/pull/1335#discussion_r1942430544
* ~~the aspect about   "module": "commonjs" vs "Node16" is taken care of in https://github.com/eclipse-thingweb/node-wot/pull/1348 , see https://github.com/eclipse-thingweb/node-wot/pull/1335#discussion_r1942425485~~
> Follow-up for PR 1335

- API.md
fix the API description of how to read a property value. 
As described in #1344
> fix API documentation for readProperty

- package.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1356
> refactor: run "npm pkg fix"

- .github/workflows/browser-test.yml
At the moment, it is not clear in the GitHub UI "what" is tested with this run
> Update browser-test.yml with clearer job name

- package-lock.json
- packages/binding-opcua/README.md
- packages/binding-opcua/package.json
- packages/binding-opcua/src/opcua-protocol-client.ts
- packages/binding-opcua/test/client-test.ts
- packages/binding-opcua/test/opcua-href-test.ts
- packages/examples/src/bindings/opcua/demo-opcua-thing-description.ts
I started to look into. Unfortunately, OPC UA protocol is blocked on my machine at the moment and I need to fix that issue first. I just coded what I *think* should work... 
~~TODO: Update readme, see https://github.com/eclipse-thingweb/node-wot/tree/master/packages/binding-opcua#form-extensions~~ https://github.com/eclipse-thingweb/node-wot/pull/1368/commits/b912d321ccb7103901b9570e268e75449dd149c5
fixes https://github.com/eclipse-thingweb/node-wot/issues/1367
> Parse nodeId from href

- .github/workflows/ci.yaml
- README.md
> chore: Node.js 18 end of life

- README.md
...both were more a subprotocol than an actual binding
> docs: remove information about *old* bindings

- packages/binding-coap/src/coap-server.ts
- packages/binding-http/src/http-server.ts
- packages/binding-websockets/src/ws-server.ts
- packages/core/src/helpers.ts
Yet another approach... (alternative for https://github.com/eclipse-thingweb/node-wot/pull/1352)
Advantages I see:
* each binding can choose the way it likes to create urls if there are thing name clashes. This is anyway a bit of a problematic case since no one can rely on the strategy since it depends on the order a thing has been added.
* no need for a helpers method
* no need to pass (and create) a set around with the existing names so far
fixes https://github.com/eclipse-thingweb/node-wot/issues/1351
> refactor: generate unique names/urls locally

- examples/templates/exposed-thing/package.json
- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-modbus/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/src/security/oauth/package.json
Note: @thingweb/thing-model needs to be updates first to get a *clean* package-lock.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1380
> chore: update Scripting TS dependencies (March 2025)

- README.md
Changes
* updated HTTP links
* removes CoAP links (since they are no longer available)
* Note: counter TD is not yet online
fixes https://github.com/eclipse-thingweb/node-wot/issues/1392
> docs: update links to online things

- packages/binding-http/src/http-client-impl.ts
- packages/core/src/wot-impl.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1403
> Improve TD validation error in requestThingDescription

- eslint.config.mjs
- packages/binding-http/src/routes/action.ts
- packages/binding-http/src/routes/property.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/core/src/helpers.ts
see https://github.com/eclipse-thingweb/node-wot/issues/1430
> refactor: removing unused variables
