- .gitignore
- packages/binding-mqtt/package.json
Public bindings must be un-ignored explicitly.
> fix: bump version for MQTT

- packages/binding-http/src/http-client-factory.ts
see https://github.com/eclipse/thingweb.node-wot/issues/37
> fix: issue 37

- packages/core/src/consumed-thing.ts
- packages/core/src/content-serdes.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/resource-listeners/action-resource-listener.ts
- packages/core/src/resource-listeners/property-resource-listener.ts
- packages/core/test/ContentSerdesTest.ts
* parse multiple parameters of content type and pass them to the codec
* pass parameters and schema during encoding and decoding
> Fix for issue eclipse/thingweb.node-wot#34

- packages/binding-coap/src/coap-server.ts
- packages/binding-http/src/http-server.ts
> fix: add the correct op to forms if readOnly or writeOnly are true

- examples/scripts/counterUriVariables.js
- packages/binding-coap/package.json
- packages/binding-http/package.json
- packages/binding-http/src/http-server.ts
- packages/binding-mqtt/package.json
- packages/binding-websockets/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/core/src/exposed-thing.ts
- packages/demo-servients/package.json
- packages/integration-tests/package.json
- packages/td-tools/package.json
- packages/td-tools/src/thing-description.ts
> feat: add support for uriVariables (at least for HTTP)

- packages/binding-http/src/http-server.ts
fix(binding-http): Add support for CORS preflight requests
closes #78
> fix(binding-http): Add support for CORS preflight requests

- packages/binding-http/src/http-client.ts
> Fix(http-client): Fix content type handling

- examples/scripts/counterUriVariables-client.js
- packages/core/package.json
- packages/core/src/consumed-thing.ts
TODO check other possible RFC6570 syntax (https://tools.ietf.org/html/rfc6570)
Work in progress (do not merge)!! will look into https://www.npmjs.com/package/uritemplate
> feat: add support for URI Variables on client side

- packages/cli/src/cli.ts
> Fix(cli): correctly read config file

- examples/scripts/counterMultiLang.js
Signed-off-by: Ege Korkan <egekorkan@gmail.com>
> fix: error in description not matching descriptions

- packages/binding-http/src/http-client.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-mqtt/src/mqtt-client-factory.ts
- packages/binding-mqtt/src/mqtt-client.ts
Update to add support for observing / unobserving properties
> Add observable properties to mqtt binding

- examples/scripts/mqtt-publish.js
- examples/scripts/mqtt-subscribe.js
- examples/scripts/wot-servient.conf.json
- packages/binding-mqtt/package.json
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/cli/src/cli-default-servient.ts
- packages/cli/src/cli.ts
- packages/cli/wot-servient.conf.json.md
Fixes [https://github.com/eclipse/thingweb.node-wot/pull/65](url)
Signed-off-by: Christian Glomb christian.glomb@siemens.com
> Support MQTT 5 and cleanup servient configuration

- examples/templates/exposed-thing/README.md
- examples/templates/exposed-thing/index.js
- examples/templates/exposed-thing/package.json
- examples/templates/exposed-thing/src/base.ts
- examples/templates/exposed-thing/tsconfig.json
Signed-off-by: Ege Korkan <egekorkan@gmail.com>
> add the Exposed Thing template guide and code

- packages/binding-coap/src/coap-server.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
Please test:
- CoAP: not sure whether cancelling of observation works properly
- MQTT: try with several content types
Signed-off-by: Christian Glomb christian.glomb@siemens.com
> CoAP and MQTT enhancements

- packages/binding-http/README.md
see https://github.com/eclipse/thingweb.node-wot/issues/157
> feat: create readme for HTTP binding package

- packages/binding-opcua/test/opcua-client-test.ts
- packages/binding-opcua/test/opcua-server.ts
I opened this pull request for fixing the tests of binding-opcua. I need some more logs from travis in order to understand what is going on.
Signed-off-by: Lukesmolo <lukesmolo@gmail.com>
> fix(binding-opcua tests): fixing tests for binding-opcua

- examples/scripts/counter.js
- packages/binding-http/src/http-server.ts
- packages/core/src/exposed-thing.ts
- packages/examples/src/scripts/counter.ts
see https://github.com/eclipse/thingweb.node-wot/issues/206
> fix: issue 206

- README.md
> Setup information for WSL users

- README.md
- packages/core/src/content-serdes.ts
> feat: add/link support more media types

- packages/core/src/consumed-thing.ts
see https://github.com/eclipse/thingweb.node-wot/issues/217
> fix: specify DataSchema of ThingAction input

- examples/scripts/counter-client.js
- packages/core/src/consumed-thing.ts
- packages/examples/src/scripts/counter-client.ts
see https://github.com/eclipse/thingweb.node-wot/issues/218
> fix: properly take InteractionOptions (e.g., uriVariables) into account

- examples/scripts/coffee-machine-client.js
- examples/scripts/coffee-machine.js
- packages/examples/src/scripts/coffee-machine-client.ts
- packages/examples/src/scripts/coffee-machine.ts
> feat: add new example script

- .dockerignore
See https://github.com/eclipse/thingweb.node-wot/pull/198#issuecomment-622609887
> Add node modules and examples to dockerignore

- examples/scripts/coffee-machine-client.js
- examples/scripts/coffee-machine.js
- packages/examples/src/scripts/coffee-machine-client.ts
- packages/examples/src/scripts/coffee-machine.ts
Closes eclipse/thingweb.website#13
> feat: change Thing name

- packages/binding-http/src/http-client.ts
see https://github.com/eclipse/thingweb.node-wot/issues/151
> fix: properly unsubscribe by stopping HTTP long polling

- examples/scripts/coffee-machine-client.js
- examples/scripts/coffee-machine-oauth.js
- examples/scripts/coffee-machine.js
- packages/examples/src/scripts/coffee-machine-client.ts
- packages/examples/src/scripts/coffee-machine-oauth.ts
- packages/examples/src/scripts/coffee-machine.ts
Closes eclipse/thingweb.website#15
> fix: fix event handling in coffee machine scripts

- packages/core/src/consumed-thing.ts
- packages/core/test/ClientTest.ts
"find" forms only that match op field
> fix: https://github.com/eclipse/thingweb.node-wot/issues/202

- packages/cli/src/cli-default-servient.ts
> fix: use default log level if not present in config file

- .vscode/launch.json
- package.json
- packages/cli/package.json
This simple PR introduces basic utility scripts for starting the default servient from the root project folder.
> Add start and debug scripts to the root project

- examples/servients/netconf-cli/package.json
- examples/servients/opcua-cli/package.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-fujitsu/package.json
- packages/binding-http/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-oracle/package.json
- packages/binding-websockets/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/td-tools/package.json
remove all "codestyle" configs in package.json
> fix: issue https://github.com/eclipse/thingweb.node-wot/issues/243

- packages/core/src/consumed-thing.ts
> fix: issue 217

- packages/binding-coap/src/coap-server.ts
- packages/binding-fujitsu/src/fujitsu-server.ts
- packages/binding-http/src/http-server.ts
- packages/binding-oracle/src/oracle-server.ts
allows users to see address and port
> chore: use info logging level for server starts

- packages/binding-coap/src/coap-server.ts
- packages/binding-fujitsu/src/fujitsu-server.ts
- packages/binding-http/src/http-server.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-oracle/src/oracle-server.ts
- symmetrical with start logging
- add MQTT start log
> fix: improve issue 254, log stop server also on info level

- packages/binding-http/README.md
A PR which adds support of SSE in HTTP binding is already in master, what I have forgot to change is, the feature matrix. 
It is done now.
> Fixed feature matrix in ReadMe

- packages/binding-http/README.md
> [binding-http] Fix readme feature matrix

- packages/binding-http/README.md
Some users were confused by this malformed JSON.
> fix(binding-http): README.md credentials json

- examples/browser/counter.html
- examples/browser/index.html
see https://github.com/eclipse/thingweb.node-wot/issues/274
> fix: issue error "Unknown theme foundation5" for some actions

- packages/cli/src/cli-default-servient.ts
> feat: merge config with defaults

- packages/core/src/consumed-thing.ts
see https://github.com/eclipse/thingweb.node-wot/issues/285
> fix: improve error handling of unknown interaction name

- README.md
> Fix modbus implementation status

- API.md
Fixes #209
Signed-off-by: ajs124 <eclipse@ajs124.de>
> feat: improve API.md

- packages/binding-file/README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/284
> feat: add readme to file binding

- Dockerfile
- README.md
> Update python to version 3

- packages/cli/README.md
- packages/cli/package.json
- packages/cli/src/cli.ts
- packages/core/src/servient.ts
- packages/core/test/RuntimeTest.ts
Closes #192. Notice that this PR is based on  #318. So it will stay in the draft mode until the other is merged.
> [CLI/Core] introduce environment variable support

- examples/browser/coffee-machine.html
- examples/browser/coffee-machine.js
- examples/browser/images/coffee-161112.svg
This PR adds a static status page for the smart coffee machine thing deployed at http://plugfest.thingweb.io:8083/smart-coffee-machine.
> feat: add coffee machine static page

- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/333
> feat: uses internal variables for reading/writing count

- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/340
> fix: pass along rejects for handlers

- packages/cli/src/cli-default-servient.ts
> fix: fix the way used protocols are checked

- packages/binding-opcua/test/opcua-client-test.ts
see https://github.com/eclipse/thingweb.node-wot/issues/349
> test: skip OPCUA tests till testing issue is resolved

- packages/binding-opcua/test/opcua-client-test.ts
- packages/binding-opcua/test/opcua-server.ts
This PR fixes #349.  Thank you @lukesmolo for the guidance. 
P.s. The issue says that the tests didn't work on windows but they actually failed also in Linux. It should be fixed now on both systems.
> Fix opcua tests

- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
API will change for v0.8.x anyway
see discussion in https://github.com/eclipse/thingweb.node-wot/issues/333
> fix: revert pr #328 for v0.7.x

- README.md
Added a short troubleshooting guide to the README.
> Add troubleshooting for "too many symbolic links encountered" 

- packages/binding-opcua/src/opcua-client.ts
- packages/core/src/exposed-thing.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/376
+ minor OPCUA fixes
> fix: write value before notifying observers

- packages/core/src/consumed-thing.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/385
> create shallow copy of form for uriVariables and update href

- packages/binding-http/src/http-server.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/389
> catch decodeURI errors gracefully

- README.md
Signed-off-by: JohannesMerkt <mailjohannesmerkt@gmail.com>
> fix: fixed and improved code example in readme

- .gitignore
- package-lock.json
- packages/binding-coap/package-lock.json
- packages/binding-file/package-lock.json
- packages/binding-fujitsu/package-lock.json
- packages/binding-http/package-lock.json
- packages/binding-modbus/package-lock.json
- packages/binding-mqtt/package-lock.json
- packages/binding-netconf/package-lock.json
- packages/binding-opcua/package-lock.json
- packages/binding-oracle/package-lock.json
- packages/binding-websockets/package-lock.json
- packages/browser-bundle/package-lock.json
- packages/cli/package-lock.json
- packages/core/package-lock.json
- packages/examples/package-lock.json
- packages/td-tools/package-lock.json
fixes https://github.com/eclipse/thingweb.node-wot/issues/395
fixes https://github.com/eclipse/thingweb.node-wot/issues/379
> chore: add package-lock.json files

- packages/core/src/content-serdes.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/399
> fix: content serdes log package name

- packages/binding-http/src/http.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/404
> fix: use correct types

- examples/scripts/counter-client.js
- packages/binding-coap/src/coap-client.ts
- packages/binding-http/src/http-client.ts
- packages/examples/src/scripts/counter-client.ts
This PR is mainly focused on fixing errors with the new stream interface. Now the counter example should work as expected.
> Streaming errors with new APis

- packages/core/src/exposed-thing.ts
- packages/core/src/wot-impl.ts
- packages/core/test/ServerTest.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/427
~~fixes https://github.com/eclipse/thingweb.node-wot/issues/426 for v.08.x~~
> Single place of input modifications

- packages/binding-coap/src/coap-server.ts
- packages/binding-fujitsu/src/fujitsu-server.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/http-server-test.ts
- packages/binding-mqtt/src/mqtt-broker-server.ts
- packages/binding-oracle/src/oracle-server.ts
- packages/binding-websockets/src/ws-server.ts
- packages/core/src/exposed-thing.ts
- packages/core/src/protocol-interfaces.ts
- packages/core/src/servient.ts
- packages/core/test/ServerTest.ts
> Implement functionality to destroy (remove) a thing

- packages/binding-modbus/src/modbus-client.ts
- packages/binding-modbus/src/modbus.ts
- packages/binding-modbus/src/utils.ts
See https://github.com/eclipse/thingweb.node-wot/issues/297#issuecomment-888973248
> Use readHoldingRegisters instead of readMultipleHoldingRegisters

- packages/core/src/consumed-thing.ts
- packages/core/test/ClientTest.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/466
> fix: take into account security at form level

- packages/binding-modbus/src/modbus-connection.ts
- packages/cli/src/cli-default-servient.ts
- packages/cli/src/cli.ts
- packages/td-tools/src/td-parser.ts
- packages/td-tools/src/td-tools.ts
- packages/td-tools/src/td-transformer.ts
- packages/td-tools/test/TDParseTest.ts
I propose doing this work in many but small portions so that everything is reviewable.
So, consider this PR as my first portion.
> refactor: align with eslint rules

- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
in TestFest it was discovered that multilang for counter should report the same value for language map
> fix: multilang the same in map

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/505
> refactor: use /properties instead of /all/properties

- README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/484
> docs: add statistics

- package.json
> Re-introduce npm run link at the root level

- .eslintrc.js
fixes https://github.com/eclipse/thingweb.node-wot/issues/595
> chore: exclude only root examples folder from eslint

- packages/binding-coap/src/coap-server.ts
The merge of #538 has caused a small problem in `coap-server.ts` which should be addressed by this PR :)
> fix(coap): resolve issue with URL pathname

- packages/binding-opcua/src/opcua-client.ts
Fix for binding-opcua handling arrays (#611)
> fix(binding-opcua): fix for #611

- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-browser.ts
- packages/binding-http/src/http-client.ts
- packages/binding-http/src/http-server.ts
- packages/binding-http/src/http.ts
- packages/binding-http/src/oauth-manager.ts
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/src/subscription-protocols.ts
- packages/binding-http/test/http-client-basic-test.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/http-server-oauth-tests.ts
- packages/binding-http/test/http-server-test.ts
- packages/binding-http/test/memory-model.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/core/src/consumed-thing.ts
This PR fixes a number of eslint issues in the `binding-http` package.
> style(http): fix eslint issues

- packages/binding-http/test/http-server-test.ts
- packages/core/src/exposed-thing.ts
see https://github.com/eclipse/thingweb.node-wot/issues/482#issuecomment-966497766
> Issue interaction input to readable

- packages/binding-firestore/src/codecs/firestore-codec.ts
- packages/binding-firestore/src/firestore-client-factory.ts
- packages/binding-firestore/src/firestore-client.ts
- packages/binding-firestore/src/firestore-handler.ts
- packages/binding-firestore/src/firestore-server.ts
- packages/binding-firestore/src/firestore.ts
- packages/binding-mbus/src/mbus-client-factory.ts
- packages/binding-mbus/src/mbus-client.ts
- packages/binding-mbus/src/mbus-connection.ts
- packages/binding-mbus/src/mbus.ts
- packages/core/src/errors.ts
Note: No code change, simply fixing headers
> chore: add/fix missing copyright headers

- packages/binding-netconf/src/async-node-netconf.ts
- packages/binding-netconf/src/codecs/netconf-codec.ts
- packages/binding-netconf/src/netconf-client.ts
- packages/binding-netconf/src/netconf.ts
- packages/binding-netconf/src/xpath2json.ts
- packages/binding-netconf/test/netconf-client-test.ts
This PR fixes a number of eslint issues in the `binding-netconf` package.
> style(binding-netconf): fix eslint issues

- package-lock.json
- packages/binding-http/package.json
- packages/binding-http/test/http-client-basic-test.ts
- packages/binding-http/test/http-client-oauth-tests.ts
- packages/binding-http/test/http-client-test.ts
- packages/binding-http/test/memory-model.ts
This PR fixes most of the linting issues in the http binding. A few `any`s had to be introduced, however, as the `InMemoryModel` defined for testing does not completely implement an OAuth2 model. This issue should probably be tackled in a follow-up PR, though.
> style(http-binding): Fix linting issues

- README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/671
see [rendered](https://github.com/eclipse/thingweb.node-wot/blob/0ffbf3aa61e130387ffff76ec15348b8ec3736b9/README.md) version.
> use drop-downs

- CODE_OF_CONDUCT.md
- SECURITY.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/688
> add code of conduct and security MD

- examples/browser/counter.js
- examples/scripts/counter.js
fixes https://github.com/eclipse/thingweb.node-wot/issues/697
> avoid issues with no data for event

- README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/671
> docs: remove details drop-downs and re-introduce TOC

- packages/binding-modbus/src/modbus-connection.ts
- packages/binding-modbus/test/test-modbus-server.ts
Another step closer to the "eslint correctness" 🥵
> style(binding-modbus): solve lint issues

- examples/browser/index.html
- examples/browser/index.js
- examples/browser/smart-coffee-machine.html
- examples/browser/smart-coffee-machine.js
see https://github.com/eclipse/thingweb.node-wot/issues/654
> fix browser remaining browser examples 

- examples/templates/exposed-thing/package.json
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
fixes https://github.com/eclipse/thingweb.node-wot/issues/703
> update wot-typescript-definitions to 0.8.0-SNAPSHOT.22

- SECURITY.md
suggested in https://gitlab.eclipse.org/eclipsefdn/emo-team/emo/-/issues/192#note_617308
> using generic Eclipse SECURITY.md

- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/705
> fix: remove internal keys from getThingDescription() call

- package-lock.json
- packages/td-tools/package.json
- packages/td-tools/src/thing-model-helpers.ts
- packages/td-tools/test/ThingModelHelperTest.ts
This should implement the second and third points of the todo list for issue #680
> Thing model

- packages/binding-http/src/http-server.ts
seems like a copy & paste error
> fix: use proper handleUnobserveProperty call instead of event

- README.md
old link/domain does not work any longer
> Use *new* statistics links

- examples/templates/exposed-thing/src/base.ts
This PR fixes the template to include all changes in 0.8.X, as it was determined that there were missing changes that needed to be incorporated. The template now also uses the async-await paradigm for a more readable experience.
> fix template and change to async-await paradigm

- package-lock.json
- packages/binding-coap/package.json
Resolves #728, resolves #724. Probably also resolves #637?
> chore(deps): bump coap to 1.0.8

- packages/examples/src/bindings/http/example-client.ts
- packages/examples/src/bindings/http/example-server-secure.ts
- packages/examples/src/bindings/http/example-server.ts
- tsconfig.json
follow-up PR for https://github.com/eclipse/thingweb.node-wot/pull/742
> chore(binding-http): add HTTP examples from README as files

- packages/core/src/interaction-output.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/747
> fix: value() might also return undefined if no value is expected

- package-lock.json
I regenerated package-lock to get ready for next release `0.8.1`.
Does this sound reasonable for everyone? We have many minor fixes/improvements and firestore binding is back also.
This makes me think we should publish an update...
@relu91 @sebastiankb @egekorkan
> chore: regenerate package-lock.json for next release

- .vscode/launch.json
- README.md
- packages/cli/README.md
clientonly to client-only
configfile to config-file
fixes https://github.com/eclipse/thingweb.node-wot/issues/772
> docs: change/align flag names

- examples/security/oauth/README.md
- examples/security/oauth/consumer.js
- examples/security/oauth/exposer.js
- examples/security/oauth/memory-model.js
- examples/security/oauth/server.js
- packages/binding-http/src/oauth-token-validation.ts
- packages/binding-http/test/oauth-token-validation-tests.ts
- packages/examples/src/security/oauth/README.md
- packages/examples/src/security/oauth/consumer.ts
- packages/examples/src/security/oauth/exposer.ts
- packages/examples/src/security/oauth/memory-model.js
- packages/examples/src/security/oauth/server.js
- packages/examples/src/security/oauth/tsconfig.json
Fixes #769. @estallio can I ask you to review it?
> Fix oAuth 2.0 in http binding

- examples/scripts/smart-coffee-machine-client.js
- examples/scripts/smart-coffee-machine.js
- examples/templates/exposed-thing/package.json
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-http/src/http-server.ts
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/core/src/exposed-thing.ts
- packages/core/test/ServerTest.ts
- packages/examples/package.json
- packages/examples/src/scripts/smart-coffee-machine-client.ts
- packages/examples/src/scripts/smart-coffee-machine.ts
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
fixes https://github.com/eclipse/thingweb.node-wot/issues/764
> fix: observable property

- packages/cli/src/cli-default-servient.ts
- packages/cli/src/cli.ts
- packages/cli/test/RuntimeTest.ts
- packages/cli/tsconfig.json
> fix CLI compilation errors due to #758

- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
see counter PR, https://github.com/w3c/wot-testing/pull/364
> feat: add links container to counter sample

- package-lock.json
- packages/binding-http/package.json
- packages/binding-mqtt/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
"wot-thing-description-types" --> "^1.1.0-20-July-2022",
"wot-thing-model-types"       --> "^1.1.0-27-July-2022",
> update wot types

- packages/core/src/codecs/base64-codec.ts
- packages/core/src/codecs/json-codec.ts
- packages/core/src/codecs/netconf-codec.ts
- packages/core/src/codecs/octetstream-codec.ts
- packages/core/src/codecs/text-codec.ts
- packages/core/src/content-serdes.ts
- packages/core/test/ContentSerdesTest.ts
Note: TD might not contain schema information
fixes https://github.com/eclipse/thingweb.node-wot/issues/753
> refactor: make schema in ContentSerdes optional

- packages/binding-coap/.eslintrc.json
fixes https://github.com/eclipse/thingweb.node-wot/issues/819
> chore: add missing .eslintrc.json file

- packages/binding-mqtt/src/mqtt-broker-server.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/838
> fix: avoid wrapping Content into Content

- packages/binding-http/src/credential.ts
- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/src/http-server.ts
- packages/cli/src/cli.ts
I have started in credentials but found some other small ones. I have a spell checker in vs code but it finds code related keywords as well. Might be nice to have some tool that is more intelligent
> [nit] typo fixes 

- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/858
> fix: call emitPropertyChange() explicitly as required

- README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/869
> docs: remove NodeJS 10/12 mentioning

- package-lock.json
- packages/browser-bundle/process
issue resolved, see https://github.com/rdfjs/N3.js/issues/310#issuecomment-1369195630
> refactor: browserify workaround no longer necessary

- packages/binding-http/src/http-client-impl.ts
- packages/binding-http/test/http-client-test.ts
> fix: add missing unsubscribe to http subscription

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/902
fixes https://github.com/eclipse/thingweb.node-wot/issues/862
> fix: take into account content type of ExposeThingInit

- packages/binding-coap/test/coap-server-test.ts
> test(binding-coap): add test for IPv6 support

- packages/examples/README.md
fixes https://github.com/eclipse/thingweb.node-wot/issues/919
> docs: remove links to folders that no longer exist

- examples/scripts/counter.js
- packages/examples/src/scripts/counter.ts
There were inconsistencies with the multiple language options. This was actually resulting in an invalid TD. I have also adjusted some description text and google translated it to other languages.
> fix: Update counter Thing

- packages/core/package.json
- packages/core/src/exposed-thing.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/947
> refactor: remove out-dated getSubjectTD concept from ExposedThing

- examples/templates/exposed-thing/package.json
- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-firestore/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/core/src/exposed-thing.ts
- packages/core/src/protocol-interfaces.ts
- packages/examples/package.json
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
"wot-typescript-definitions": "0.8.0-SNAPSHOT.25"
"wot-thing-description-types": "1.1.0-23-March-2023"
> update TS definitions

- examples/testthing/testthing.js
- packages/examples/src/testthing/testthing.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/966
> TestThing - fire events on write

- package-lock.json
- packages/td-tools/package.json
> chore: update TM dependency version

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
fixes https://github.com/eclipse/thingweb.node-wot/issues/949
~~https://github.com/eclipse/thingweb.node-wot/issues/965~~
> fix: properly identify readall and writeall op's

- packages/binding-http/src/http-server.ts
- packages/binding-http/test/http-server-test.ts
Fix #1000. (we reached a nice milestone)
> Prefer application/td+json when is possibile instead of text/html 

- .eslintrc.js
- package-lock.json
- package.json
- packages/core/test/InteractionOutputTest.ts
- packages/core/test/ProtocolHelpersTest.ts
- packages/examples/package.json
> Upgrade eslint workspaces plugin

- .github/CODEOWNERS
@egekorkan is now an *official* committer 👍
> chore: update CODEOWNERS file with @egekorkan

- packages/binding-file/src/file-client.ts
- packages/binding-file/tsconfig.json
relevant for to https://github.com/eclipse-thingweb/node-wot/issues/758
> strict tsconfig checks in place for binding-file

- examples/quickstart/simple-coffee-machine.js
- packages/examples/src/quickstart/simple-coffee-machine.ts
Introducing a new affordance for the quickstart machine. It helps to reset the resources.
> feat(examples/quickstart): add a refill action for coffe-machine

- packages/binding-http/README.md
fixes https://github.com/eclipse-thingweb/node-wot/issues/1090
> docs: Update HTTP README.md with UrlRewrite

- package-lock.json
- package.json
- packages/binding-coap/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/examples/src/security/oauth/package.json
- packages/td-tools/package.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1101
> chore: update TS definitions

- package-lock.json
- packages/binding-coap/package.json
- packages/binding-file/package.json
- packages/binding-http/package.json
- packages/binding-mbus/package.json
- packages/binding-modbus/package.json
- packages/binding-mqtt/package.json
- packages/binding-netconf/package.json
- packages/binding-opcua/package.json
- packages/binding-websockets/package.json
- packages/browser-bundle/package.json
- packages/cli/package.json
- packages/core/package.json
- packages/examples/package.json
- packages/td-tools/package.json
FYI: Every time I update the node-wot package versions I also newly create `package-lock.json` to update to recent dependencies. Hence you see many changes for `package-lock.json` ...
> chore: increase version numbers to 0.8.10 for next release

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1142
> feat: add semanticId/supplementalSemanticIds for AID terms

- package-lock.json
- packages/cli/package.json
- packages/examples/src/security/oauth/package.json
> chore: upgrade ts-node to 10.9.1

- README.md
- packages/binding-file/README.md
- packages/binding-http/README.md
- packages/binding-mqtt/README.md
- packages/td-tools/README.md
fixes https://github.com/eclipse-thingweb/node-wot/issues/1187
> docs: align import/require style in READMEs

- README.md
I removed the title because it was redundant. Let me know if you want to integrate it differently
> docs(README): introduce the new logo

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- packages/td-tools/test/util/inverterModbus.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1223
> refactor: add AID support for terms created/modified/support

- packages/td-tools/src/util/asset-interface-description.ts
- packages/td-tools/test/AssetInterfaceDescriptionTest.ts
- packages/td-tools/test/util/AIDSchema.json
- packages/td-tools/test/util/inverterModbus.json
fixes https://github.com/eclipse-thingweb/node-wot/issues/1225
> Handle AID terms on affordance level and form level

- packages/td-tools/src/util/asset-interface-description.ts
see https://github.com/eclipse-thingweb/node-wot/issues/1235#issuecomment-2011969629
> Update asset-interface-description semanticID

- packages/binding-mqtt/src/mqtt-client.ts
Super minor fix, but now I'm scared of anything that is not awaited 😆
> fix(binding-mqtt/mqtt-client): add missing await

- packages/binding-http/test/credential-test.ts
fixing minor typo in suite name
> fix(typo): in credential-test.ts

- packages/binding-modbus/test/modbus-client-test.ts
fixes https://github.com/eclipse-thingweb/node-wot/issues/1287
> refactor: fix warning in VS code

- packages/binding-http/README.md
fixes https://github.com/eclipse-thingweb/node-wot/issues/1337
> Update SSE details

- API.md
fixes https://github.com/eclipse-thingweb/node-wot/issues/801
> docs: align with the current form/code-style and counter example
